# Generated by Django 5.2.10 on 2026-06-19 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='A unique internal identification code assigned to the employee.', max_length=50, unique=True)),
                ('department', models.CharField(choices=[('asset_mgmt', 'Asset Management'), ('wealth_mgmt', 'Wealth Management & RMs'), ('compliance_legal', 'Compliance & Legal'), ('risk_mgmt', 'Risk Management'), ('operations', 'Operations & Settlements'), ('finance_acc', 'Finance & Accounts'), ('research', 'Investment Research & Analytics'), ('tech', 'Technology & Systems')], help_text='The specific functional department within the financial institution.', max_length=30)),
                ('designation', models.CharField(choices=[('ceo', 'Chief Executive Officer'), ('cio', 'Chief Investment Officer'), ('cco', 'Chief Compliance Officer'), ('portfolio_mgr', 'Portfolio Manager'), ('analyst', 'Investment Analyst'), ('research_head', 'Head of Research'), ('wealth_mgr', 'Wealth Manager'), ('senior_rm', 'Senior Relationship Manager'), ('rm', 'Relationship Manager'), ('compliance_off', 'Compliance Officer'), ('risk_off', 'Risk Officer'), ('ops_assoc', 'Operations Associate')], help_text="The employee's official role and structural hierarchy level.", max_length=30)),
                ('branch', models.CharField(blank=True, help_text='The physical or localized branch office the employee belongs to.', max_length=100, null=True)),
                ('rm_code', models.CharField(blank=True, help_text='The specific Relationship Manager (RM) code, if applicable.', max_length=20, null=True)),
                ('role', models.CharField(choices=[('client', 'Client / Investor'), ('rm', 'Relationship Manager'), ('compliance_l1', 'Compliance Officer L1'), ('senior_mgmt', 'Senior Management'), ('compliance_final', 'Compliance Final Sign-off'), ('admin', 'System Administrator')], default='client', help_text='The system access role defining permissions and workflows for this user.', max_length=20)),
                ('market', models.CharField(choices=[('PSX', 'Pakistan Stock Exchange'), ('US', 'US Equities'), ('GCC', 'GCC Region'), ('SARWA', 'SARWA Platform'), ('ALL', 'All Markets')], default='PSX', help_text='The primary financial market this staff member is authorized to operate in (e.g., PSX).', max_length=10)),
                ('is_active_staff', models.BooleanField(default=True, help_text='Designates whether this staff member is currently active in the organization.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The administrative user who initially created this staff profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
                ('reports_to', models.ForeignKey(blank=True, help_text='The direct manager this employee reports to. Creates the Org Chart.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.staffprofile')),
                ('user', models.OneToOneField(help_text='The base user account linked to this staff profile.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_staff_profile',
            },
        ),
    ]
