# Generated by Django 5.2.10 on 2026-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_code',
            field=models.CharField(help_text='A unique {P00100} code assigned to the employee.', max_length=50, unique=True),
        ),
    ]
