# Generated by Django 5.2.10 on 2026-02-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsector',
            name='local_code',
            field=models.CharField(help_text='Sector Code e.g. 820', max_length=20),
        ),
        migrations.AlterField(
            model_name='localsector',
            name='name',
            field=models.CharField(help_text='Local Sector Name e.g.,OIL & GAS EXPLORATION COMPANIES', max_length=200),
        ),
    ]
