# Generated by Django 5.2.10 on 2026-02-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_localsector_local_code_alter_localsector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsectorgicsmap',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Confidence of mapping data manual, vendor or import', max_digits=5),
        ),
        migrations.AlterField(
            model_name='localsectorgicsmap',
            name='gics_subindustry',
            field=models.ForeignKey(help_text='GICS subindustry (edition-aware).', on_delete=django.db.models.deletion.PROTECT, related_name='local_maps', to='taxonomy.gicssubindustry'),
        ),
        migrations.AlterField(
            model_name='localsectorgicsmap',
            name='source',
            field=models.CharField(default='manual', help_text='Source of mapping data manual, vendor or import', max_length=50),
        ),
    ]
