# Generated by Django 5.2.10 on 2026-02-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Currency code (e.g. USD, PKR, AED)', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.TextField(help_text='Currency Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='numeric_code',
            field=models.PositiveIntegerField(blank=True, help_text='ISO 4217 numeric code for currency', null=True),
        ),
    ]
