# Generated by Django 5.2.10 on 2026-02-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_currency_code_alter_currency_currency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='base_currency',
            field=models.ForeignKey(db_column='base_currency_id', help_text='Base currency e.g. USD', on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_base', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='code',
            field=models.TextField(blank=True, help_text='Currency code (e.g. USD/PKR)', null=True),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='quote_currency',
            field=models.ForeignKey(db_column='quote_currency_id', help_text='Quote currency e.g. Pkr', on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_quote', to='masters.currency'),
        ),
    ]
