# Generated by Django 5.2.10 on 2026-02-06 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_currencypair_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_code',
            field=models.CharField(help_text='Broker Code e.g. SCS', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_name',
            field=models.CharField(help_text='Broker Full name', max_length=200),
        ),
        migrations.AlterField(
            model_name='broker',
            name='default_base_currency',
            field=models.ForeignKey(blank=True, help_text='Optional default currency for all currencies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_base_currency', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address for this broker.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for this broker.', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number for this broker.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='regulator',
            field=models.CharField(blank=True, help_text='Optional regulator for this broker.', max_length=80, null=True),
        ),
    ]
