# Generated by Django 5.2.10 on 2026-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_broker_broker_code_alter_broker_broker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='broker_type',
            field=models.CharField(choices=[('BRK', 'Broker'), ('CUS', 'Custodian'), ('PLT', 'Platform'), ('BNK', 'Bank'), ('EX', 'Exchange')], default='BRK', max_length=3),
        ),
    ]
