# Generated by Django 5.2.10 on 2026-02-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_broker_broker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Currency code (e.g. USD, PKR, AED)', max_length=12, unique=True),
        ),
    ]
