# Generated by Django 5.2.10 on 2026-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='settlement_offset',
            field=models.IntegerField(default=0, help_text='Number of days for settlement (e.g., 0 for T+0, 1 for T+1)'),
        ),
    ]
