# Generated by Django 5.2.10 on 2026-06-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_exchange_settlement_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='exchange',
            field=models.ForeignKey(blank=True, help_text='Primary exchange this broker is listed on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='masters.exchange'),
        ),
    ]
