# Generated by Django 5.2.10 on 2026-06-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_broker_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('counterparty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Canonical short code.', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Counterparty display name.', max_length=150)),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal name.', max_length=200, null=True)),
                ('counterparty_type', models.CharField(choices=[('BANK', 'Bank'), ('BROKER_DEALER', 'Broker / Dealer'), ('CUSTODIAN', 'Custodian'), ('OTC_DEALER', 'OTC Dealer'), ('OTHER', 'Other')], help_text='Bank, broker-dealer, custodian, OTC dealer, or other.', max_length=20)),
                ('lei', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='counterparties', to='masters.country')),
            ],
            options={
                'db_table': 'counterparty',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Canonical code, e.g. SARWA, ETORO, WAHDA.', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Platform display name.', max_length=100)),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal entity or operator name.', max_length=150, null=True)),
                ('regulator_name', models.CharField(blank=True, help_text='Regulator Name e.g. SECP, SEC, ADGM', max_length=100, null=True)),
                ('license_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('domicile_country', models.ForeignKey(blank=True, db_column='domicile_country_id', db_constraint=False, help_text='Country of incorporation or registration.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='platforms_domiciled', to='masters.country')),
                ('operating_country', models.ForeignKey(blank=True, db_column='operating_country_id', db_constraint=False, help_text='Primary operating country, if different from domicile.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='platforms_operated', to='masters.country')),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='ExecutionVenue',
            fields=[
                ('execution_venue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Canonical code, e.g. PSX, SARWA, JPM_OTC, XOFF.', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name of the execution venue.', max_length=100)),
                ('venue_type', models.CharField(choices=[('EXCHANGE', 'Exchange'), ('PLATFORM', 'Platform'), ('COUNTERPARTY', 'Counterparty'), ('OTC', 'OTC'), ('INTERNAL', 'Internal')], help_text='Exchange, platform, counterparty, OTC, or internal.', max_length=20)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_venues', to='masters.counterparty')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_venues', to='masters.exchange')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_venues', to='masters.platform')),
            ],
            options={
                'db_table': 'execution_venue',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('counterparty__isnull', True), ('exchange__isnull', False), ('platform__isnull', True), ('venue_type', 'EXCHANGE')), models.Q(('venue_type', 'EXCHANGE'), _negated=True), _connector='OR'), name='ck_exec_venue_exchange_only'), models.CheckConstraint(condition=models.Q(models.Q(('counterparty__isnull', True), ('exchange__isnull', True), ('platform__isnull', False), ('venue_type', 'PLATFORM')), models.Q(('venue_type', 'PLATFORM'), _negated=True), _connector='OR'), name='ck_exec_venue_platform_only'), models.CheckConstraint(condition=models.Q(models.Q(('counterparty__isnull', False), ('exchange__isnull', True), ('platform__isnull', True), ('venue_type', 'COUNTERPARTY')), models.Q(('venue_type', 'COUNTERPARTY'), _negated=True), _connector='OR'), name='ck_exec_venue_counterparty_only'), models.CheckConstraint(condition=models.Q(models.Q(('counterparty__isnull', True), ('exchange__isnull', True), ('platform__isnull', True), ('venue_type__in', ['OTC', 'INTERNAL'])), models.Q(('venue_type__in', ['OTC', 'INTERNAL']), _negated=True), _connector='OR'), name='ck_exec_venue_otc_internal_empty_refs')],
            },
        ),
    ]
