# Generated by Django 5.2.10 on 2026-02-02 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_remove_securitymaster_primary_listing'),
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
        ('portfolio', '0003_alter_portfolio_mandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IborTrade',
            fields=[
                ('trd_id', models.BigAutoField(db_column='trd_id', primary_key=True, serialize=False)),
                ('side_cd', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], db_column='side_cd', help_text='Trade side: B=Buy, S=Sell.', max_length=1)),
                ('qty', models.DecimalField(db_column='qty', decimal_places=8, help_text='Executed quantity. Use positive numbers; side indicates direction.', max_digits=24)),
                ('px', models.DecimalField(db_column='px', decimal_places=10, help_text='Executed price in listing price currency.', max_digits=24)),
                ('trd_ts', models.DateTimeField(db_column='trd_ts', db_index=True, default=django.utils.timezone.now, help_text='Execution timestamp (trade time).')),
                ('stl_dt', models.DateField(blank=True, db_column='stl_dt', db_index=True, help_text='Settlement/value date. Drives pending vs settled cash.', null=True)),
                ('gross_amt', models.DecimalField(blank=True, db_column='gross_amt', decimal_places=10, help_text='Gross consideration in trade currency. Optional if derived = qty*px.', max_digits=28, null=True)),
                ('fees_amt', models.DecimalField(db_column='fees_amt', decimal_places=6, default=0, help_text='Total fees/commission in trade currency (positive number).', max_digits=18)),
                ('tax_amt', models.DecimalField(db_column='tax_amt', decimal_places=6, default=0, help_text='Taxes/levies/withholding applied to this trade in trade currency.', max_digits=18)),
                ('net_amt', models.DecimalField(blank=True, db_column='net_amt', decimal_places=10, help_text='Net cash impact in trade currency (buy is typically negative, sell positive). Optional if derived.', max_digits=28, null=True)),
                ('ext_ref', models.CharField(blank=True, db_column='ext_ref', help_text='External reference (broker exec id, venue trade id, import reference).', max_length=80, null=True)),
                ('src_cd', models.CharField(choices=[('MAN', 'Manual'), ('OMS', 'OMS'), ('VEN', 'Venue/API'), ('IMP', 'Import')], db_column='src_cd', db_index=True, default='MAN', help_text='Where this trade came from (manual/OMS/venue/import).', max_length=3)),
                ('sts_cd', models.CharField(choices=[('BOK', 'Booked'), ('CXL', 'Cancelled'), ('REV', 'Reversed'), ('PND', 'Pending')], db_column='sts_cd', db_index=True, default='BOK', help_text='Booking status (booked/cancelled/reversed).', max_length=3)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', help_text='Free text notes for ops/audit.', max_length=255)),
                ('crt_by', models.IntegerField(db_column='crt_by', default=101, help_text='Created by user id.')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, db_column='crt_ts', help_text='Create timestamp.')),
                ('upd_ts', models.DateTimeField(auto_now=True, db_column='upd_ts', help_text='Update timestamp.')),
                ('acct', models.ForeignKey(db_column='acct_id', help_text='Booking account. All trades are booked at account level (institution standard).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='portfolio.account')),
                ('listing', models.ForeignKey(db_column='list_id', help_text='Tradable object (ticker+venue+currency). Trades link to listing, not the master instrument.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='instruments.securitylisting')),
                ('trd_ccy', models.ForeignKey(db_column='trd_ccy_id', help_text='Trade/price currency. Usually equals listing price currency; stored for audit/snapshot.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='masters.currency')),
            ],
            options={
                'verbose_name': 'IBOR Trade',
                'verbose_name_plural': 'IBOR Trades',
                'db_table': 'px_trd',
                'ordering': ['-trd_ts'],
            },
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('cash_id', models.BigAutoField(db_column='cash_id', primary_key=True, serialize=False)),
                ('amt', models.DecimalField(db_column='amt', decimal_places=10, help_text='Signed amount. Positive=inflow, Negative=outflow.', max_digits=28)),
                ('typ_cd', models.CharField(choices=[('TRD', 'Trade'), ('FEE', 'Fee'), ('TAX', 'Tax'), ('DEP', 'Deposit'), ('WDR', 'Withdrawal'), ('DIV', 'Dividend'), ('INT', 'Interest'), ('FX', 'FX Transfer'), ('ADJ', 'Adjustment')], db_column='typ_cd', db_index=True, default='TRD', help_text='Cash entry type (trade, fee, dividend, etc.).', max_length=3)),
                ('eff_dt', models.DateField(blank=True, db_column='eff_dt', db_index=True, help_text='Value/settlement date when cash becomes effective (settled).', null=True)),
                ('book_ts', models.DateTimeField(db_column='book_ts', db_index=True, default=django.utils.timezone.now, help_text='Book timestamp (when entry was recorded).')),
                ('sts_cd', models.CharField(choices=[('PND', 'Pending'), ('SET', 'Settled'), ('CXL', 'Cancelled')], db_column='sts_cd', db_index=True, default='PND', help_text='Pending vs settled. A nightly job can flip PND->SET when eff_dt <= today.', max_length=3)),
                ('ref_txt', models.CharField(blank=True, db_column='ref_txt', default='', help_text='Reference text (bank ref, broker ref, narrative).', max_length=120)),
                ('crt_by', models.IntegerField(db_column='crt_by', default=101, help_text='Created by user id.')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, db_column='crt_ts', help_text='Create timestamp.')),
                ('upd_ts', models.DateTimeField(auto_now=True, db_column='upd_ts', help_text='Update timestamp.')),
                ('acct', models.ForeignKey(db_column='acct_id', help_text='Account impacted by this cash entry.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='portfolio.account')),
                ('ccy', models.ForeignKey(db_column='ccy_id', help_text='Currency of the cash entry.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='masters.currency')),
                ('trd', models.ForeignKey(blank=True, db_column='trd_id', help_text='Optional link to the trade that generated this cash movement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='ibor.ibortrade')),
            ],
            options={
                'verbose_name': 'Cash Ledger Entry',
                'verbose_name_plural': 'Cash Ledger',
                'db_table': 'px_cash_led',
                'ordering': ['-book_ts'],
            },
        ),
        migrations.CreateModel(
            name='PositionLot',
            fields=[
                ('lot_id', models.BigAutoField(db_column='lot_id', primary_key=True, serialize=False)),
                ('open_qty', models.DecimalField(db_column='open_qty', decimal_places=8, help_text='Open quantity remaining in this lot.', max_digits=24)),
                ('unit_cost', models.DecimalField(db_column='unit_cost', decimal_places=10, help_text='Unit cost (price) for this lot in cost_ccy.', max_digits=24)),
                ('open_dt', models.DateField(db_column='open_dt', help_text='Lot open date (trade date).')),
                ('crt_by', models.IntegerField(db_column='crt_by', default=101, help_text='Created by user id.')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, db_column='crt_ts', help_text='Create timestamp.')),
                ('upd_ts', models.DateTimeField(auto_now=True, db_column='upd_ts', help_text='Update timestamp.')),
                ('acct', models.ForeignKey(db_column='acct_id', help_text='Account that owns this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='position_lots', to='portfolio.account')),
                ('cost_ccy', models.ForeignKey(db_column='cost_ccy_id', help_text='Currency of the lot cost basis (usually trade currency).', on_delete=django.db.models.deletion.PROTECT, related_name='position_lots', to='masters.currency')),
                ('listing', models.ForeignKey(db_column='list_id', help_text='Listing this lot belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='position_lots', to='instruments.securitylisting')),
                ('src_trd', models.ForeignKey(db_column='src_trd_id', help_text='Trade that opened this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='opened_lots', to='ibor.ibortrade')),
            ],
            options={
                'verbose_name': 'Position Lot',
                'verbose_name_plural': 'Position Lots',
                'db_table': 'px_pos_lot',
            },
        ),
        migrations.AddIndex(
            model_name='ibortrade',
            index=models.Index(fields=['acct', 'trd_ts'], name='ix_trd_acct_ts'),
        ),
        migrations.AddIndex(
            model_name='ibortrade',
            index=models.Index(fields=['listing', 'trd_ts'], name='ix_trd_list_ts'),
        ),
        migrations.AddIndex(
            model_name='ibortrade',
            index=models.Index(fields=['sts_cd', 'trd_ts'], name='ix_trd_sts_ts'),
        ),
        migrations.AddIndex(
            model_name='cashledger',
            index=models.Index(fields=['acct', 'ccy', 'sts_cd'], name='ix_cash_acct_ccy_sts'),
        ),
        migrations.AddIndex(
            model_name='cashledger',
            index=models.Index(fields=['eff_dt', 'sts_cd'], name='ix_cash_eff_sts'),
        ),
        migrations.AddIndex(
            model_name='positionlot',
            index=models.Index(fields=['acct', 'listing'], name='ix_lot_acct_list'),
        ),
    ]
