# Generated by Django 5.2.10 on 2026-02-05 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0001_initial'),
        ('instruments', '0003_remove_securitymaster_primary_listing'),
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
        ('portfolio', '0003_alter_portfolio_mandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibortrade',
            name='acct',
        ),
        migrations.RemoveField(
            model_name='ibortrade',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='ibortrade',
            name='trd_ccy',
        ),
        migrations.CreateModel(
            name='IborFxOverride',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('rate_dt', models.DateField(help_text='Date this override applies to.')),
                ('rate', models.DecimalField(decimal_places=10, help_text='Override rate with the same convention as masters: 1 base = rate quote.', max_digits=28)),
                ('reason', models.CharField(blank=True, default='', help_text='Why override was needed (missing rate, vendor issue, etc.).', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency_pair', models.ForeignKey(help_text='Currency pair being overridden.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_fx_overrides', to='masters.currencypair')),
                ('portfolio', models.ForeignKey(blank=True, help_text='Optional: restrict override to one portfolio. Null = global override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fx_overrides', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'ibor_fx_ovr',
            },
        ),
        migrations.CreateModel(
            name='IborPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('price_dt', models.DateField(help_text='Price as-of date (EOD close for daily valuation in V1).')),
                ('price', models.DecimalField(decimal_places=10, help_text='Price value for the listing.', max_digits=28)),
                ('source', models.CharField(blank=True, default='MANUAL', help_text='Price source identifier (ExchangeRate-API, MANUAL, PSX, Bloomberg, etc.).', max_length=60)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('price_ccy', models.ForeignKey(help_text='Currency of the price (usually listing currency).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_price_snaps', to='masters.currency')),
                ('security_listing', models.ForeignKey(help_text='Security listing being priced (e.g., BOP@PSX).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_price_snaps', to='instruments.securitylisting')),
            ],
            options={
                'db_table': 'ibor_px_snap',
            },
        ),
        migrations.CreateModel(
            name='IborSourceDoc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('doc_type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EMAIL', 'Email'), ('API', 'API'), ('OTHER', 'Other')], default='PDF', help_text='Type of source document used in ingestion.', max_length=10)),
                ('source_system', models.CharField(help_text="Adapter/system identifier (e.g., 'psx_broker_x', 'sarwa', 'manual').", max_length=40)),
                ('source_ref', models.CharField(blank=True, default='', help_text='External reference for the doc (email msg-id, broker statement id, etc.).', max_length=120)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original filename (if uploaded).', max_length=255)),
                ('file_sha256', models.CharField(blank=True, default='', help_text='Optional hash for deduplication and audit.', max_length=64)),
                ('received_at', models.DateTimeField(blank=True, help_text='When the doc was received (email time, download time, etc.).', null=True)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Optional extracted raw text (store only if helpful for audit/debug).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ibor_src_doc',
            },
        ),
        migrations.CreateModel(
            name='IborIngestBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_system', models.CharField(help_text='Adapter/system identifier (same meaning as on source doc).', max_length=40)),
                ('run_notes', models.TextField(blank=True, default='', help_text='Notes about parsing run, errors, warnings, etc.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('source_doc', models.ForeignKey(blank=True, help_text='The document that produced this batch (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_batches', to='ibor.iborsourcedoc')),
            ],
            options={
                'db_table': 'ibor_ing_batch',
            },
        ),
        migrations.CreateModel(
            name='IborStagedTrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('source_system', models.CharField(help_text="Adapter/system identifier (e.g., 'psx_broker_x').", max_length=40)),
                ('external_ref', models.CharField(blank=True, default='', help_text='Broker voucher/contract note id (or best available unique ref).', max_length=120)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Needs review'), ('REJ', 'Rejected'), ('APP', 'Approved'), ('POSTED', 'Posted')], default='NEW', help_text='Ops Inbox status for review/approval lifecycle.', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw parsed fields from the source (keep broker-specific info here).')),
                ('portfolio_code', models.CharField(blank=True, default='', help_text='Portfolio identifier from broker/source (to be mapped).', max_length=60)),
                ('instrument_code', models.CharField(blank=True, default='', help_text='Symbol/ISIN/ticker from broker/source (to be mapped).', max_length=80)),
                ('side', models.CharField(blank=True, default='', help_text='BUY/SELL as parsed (normalize during posting).', max_length=4)),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, help_text='Trade quantity (supports fractional shares for platforms like Sarwa).', max_digits=28, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, help_text='Trade price (as parsed).', max_digits=28, null=True)),
                ('trade_ccy', models.CharField(blank=True, default='', help_text='Trade currency ISO3 (e.g., PKR, USD, AED).', max_length=3)),
                ('trade_dt', models.DateField(blank=True, help_text='Trade date (as parsed).', null=True)),
                ('settle_dt', models.DateField(blank=True, help_text='Settlement date (as parsed).', null=True)),
                ('mapping_errors', models.JSONField(blank=True, default=dict, help_text='Mapping/validation errors (instrument not found, bad currency, duplicates etc.).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ingest_batch', models.ForeignKey(help_text='Which ingest batch produced this staged record.', on_delete=django.db.models.deletion.CASCADE, related_name='staged_trades', to='ibor.iboringestbatch')),
            ],
            options={
                'db_table': 'ibor_stg_trd',
            },
        ),
        migrations.CreateModel(
            name='IborTradeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('source_system', models.CharField(help_text="Adapter/system identifier (e.g., 'psx_broker_x', 'sarwa', 'manual').", max_length=40)),
                ('external_ref', models.CharField(blank=True, default='', help_text='Broker voucher/contract note id (should be stable for dedupe).', max_length=120)),
                ('version_no', models.PositiveIntegerField(default=1, help_text='Version number for the same external_ref (CORR creates a new version).')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='BUY or SELL.', max_length=4)),
                ('quantity', models.DecimalField(decimal_places=10, help_text='Trade quantity (supports fractional shares).', max_digits=28)),
                ('price', models.DecimalField(decimal_places=10, help_text='Trade price per unit.', max_digits=28)),
                ('trade_dt', models.DateField(help_text='Trade date (economic date).')),
                ('settle_dt', models.DateField(help_text='Settlement date (cash/security movement date).')),
                ('gross_amount', models.DecimalField(decimal_places=10, help_text='Gross = quantity * price in trade_ccy (before charges).', max_digits=28)),
                ('net_amount', models.DecimalField(decimal_places=10, help_text='Net amount after charges (in settlement currency logic).', max_digits=28)),
                ('state_cd', models.CharField(choices=[('EXEC', 'Executed'), ('CONF', 'Confirmed'), ('SETTLED', 'Settled'), ('CXL', 'Canceled'), ('CORR', 'Corrected')], default='EXEC', help_text='Lifecycle state for truth level selection (EXEC/CONF/SETTLED/CXL/CORR).', max_length=10)),
                ('state_ts', models.DateTimeField(blank=True, help_text='Timestamp when current state was achieved (optional).', null=True)),
                ('memo', models.TextField(blank=True, default='', help_text='Optional free-text notes (parsing notes, ops adjustments, etc.).')),
                ('asset_class', models.ForeignKey(blank=True, help_text='Optional snapshot of asset class at trade time. Prefer deriving from instrument.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='instruments.assetclass')),
                ('asset_sub_class', models.ForeignKey(blank=True, help_text='Optional snapshot of asset sub-class at trade time. Prefer deriving from instrument.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='instruments.assetsubclass')),
                ('broker', models.ForeignKey(blank=True, help_text='Broker/counterparty executing or confirming the trade (optional in V1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='masters.broker')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('exec_venue', models.ForeignKey(blank=True, help_text='Execution venue/exchange (PSX, NASDAQ, OTC venue). Optional; can default from instrument.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='masters.exchange')),
                ('instrument', models.ForeignKey(help_text='Instrument master key (map symbol/ISIN/ticker into this).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='instruments.securitylisting')),
                ('portfolio', models.ForeignKey(help_text='Portfolio owning the position (multi-base supported via portfolio.base_ccy).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='portfolio.portfolio')),
                ('replaces_trade', models.ForeignKey(blank=True, help_text='If this is a correction, points to the trade it replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_trades', to='ibor.ibortradeevent')),
                ('settle_ccy', models.ForeignKey(blank=True, help_text='Settlement currency (optional; defaults to trade_ccy if null).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibor_settle_ccy_trades', to='masters.currency')),
                ('trade_ccy', models.ForeignKey(help_text='Trade/contract currency (ISO3 from masters).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trade_ccy_trades', to='masters.currency')),
            ],
            options={
                'db_table': 'ibor_trd_evt',
            },
        ),
        migrations.CreateModel(
            name='IborTaxLot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('acquired_dt', models.DateField(help_text='Acquisition date (usually trade_dt).')),
                ('open_qty', models.DecimalField(decimal_places=10, help_text='Original lot quantity.', max_digits=28)),
                ('remaining_qty', models.DecimalField(decimal_places=10, help_text='Remaining lot quantity after FIFO consumptions.', max_digits=28)),
                ('unit_cost', models.DecimalField(decimal_places=10, help_text='Unit cost including allocated charges (in cost_ccy).', max_digits=28)),
                ('cost_ccy', models.ForeignKey(help_text='Cost currency ISO3 (typically portfolio base or trade currency per policy).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_lot_cost_ccy', to='masters.currency')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(help_text='Instrument for this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_lots', to='instruments.securitylisting')),
                ('portfolio', models.ForeignKey(help_text='Portfolio owning this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_lots', to='portfolio.portfolio')),
                ('trade', models.ForeignKey(help_text='BUY trade event that created this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='created_lots', to='ibor.ibortradeevent')),
            ],
            options={
                'db_table': 'ibor_lot_inv',
            },
        ),
        migrations.CreateModel(
            name='IborLotConsumption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('consumed_qty', models.DecimalField(decimal_places=10, help_text='Quantity consumed from this lot (FIFO).', max_digits=28)),
                ('unit_cost', models.DecimalField(decimal_places=10, help_text='Unit cost used for this consumption (copied from lot at time of consumption).', max_digits=28)),
                ('cost_basis', models.DecimalField(decimal_places=10, help_text='Total cost basis consumed = consumed_qty * unit_cost.', max_digits=28)),
                ('cost_ccy', models.ForeignKey(help_text='Currency of the cost basis.', on_delete=django.db.models.deletion.PROTECT, related_name='lot_consumptions_currency', to='masters.currency')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(help_text='Lot that was consumed.', on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='ibor.ibortaxlot')),
                ('sell_trade', models.ForeignKey(help_text='SELL trade that consumed lots.', on_delete=django.db.models.deletion.PROTECT, related_name='lot_consumptions', to='ibor.ibortradeevent')),
            ],
            options={
                'db_table': 'ibor_lot_cns',
            },
        ),
        migrations.CreateModel(
            name='IborChargeComponent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('charge_type_cd', models.CharField(choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='OTHER', help_text='Normalized charge category (COMM/TAX/LEVY/VAT/etc.).', max_length=10)),
                ('description', models.CharField(blank=True, default='', help_text="Broker label (e.g., 'PSX Laga', 'SST', 'SEC fee').", max_length=120)),
                ('rate', models.DecimalField(blank=True, decimal_places=10, help_text='Optional rate (percent/bps) if available from source.', max_digits=18, null=True)),
                ('amount', models.DecimalField(decimal_places=10, help_text='Charge amount (positive number).', max_digits=28)),
                ('currency', models.CharField(help_text='Charge currency ISO3.', max_length=3)),
                ('is_withholding', models.BooleanField(default=False, help_text='True if this is withholding tax (useful later for dividends/corporate actions).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(help_text='Trade that this charge belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='ibor.ibortradeevent')),
            ],
            options={
                'db_table': 'ibor_chg_cmp',
            },
        ),
        migrations.CreateModel(
            name='IborCashEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('amount', models.DecimalField(decimal_places=10, help_text='Signed cash amount: +inflow, -outflow.', max_digits=28)),
                ('effective_dt', models.DateField(help_text='Date when cash movement is effective for cash ladder.')),
                ('cash_event_type', models.CharField(choices=[('TRADE_SETTLE', 'Trade settlement'), ('TRADE_FEE', 'Trade fee/charges'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FX_CONV', 'FX conversion'), ('OTHER', 'Other')], default='OTHER', help_text='Type/category of cash movement.', max_length=20)),
                ('description', models.CharField(blank=True, default='', help_text='Free text description (broker label, reason, etc.).', max_length=200)),
                ('state_cd', models.CharField(choices=[('EXEC', 'Executed'), ('CONF', 'Confirmed'), ('SETTLED', 'Settled'), ('CXL', 'Canceled'), ('CORR', 'Corrected')], default='CONF', help_text='Lifecycle state of cash event (can mirror trade state).', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Trade/contract currency (ISO3 from masters).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_cash_ccy_trades', to='masters.currency')),
                ('portfolio', models.ForeignKey(help_text='Portfolio whose cash is impacted.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_cash_events', to='portfolio.portfolio')),
                ('trade', models.ForeignKey(blank=True, help_text='If cash event is caused by a trade settlement/fee, link to the trade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_events', to='ibor.ibortradeevent')),
            ],
            options={
                'db_table': 'ibor_csh_evt',
            },
        ),
        migrations.AlterField(
            model_name='positionlot',
            name='src_trd',
            field=models.ForeignKey(db_column='src_trd_id', help_text='Trade that opened this lot.', on_delete=django.db.models.deletion.PROTECT, related_name='opened_lots', to='ibor.ibortradeevent'),
        ),
        migrations.CreateModel(
            name='IborTradeStateHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('from_state', models.CharField(blank=True, choices=[('EXEC', 'Executed'), ('CONF', 'Confirmed'), ('SETTLED', 'Settled'), ('CXL', 'Canceled'), ('CORR', 'Corrected')], help_text='Previous state (null if first state record).', max_length=10, null=True)),
                ('to_state', models.CharField(choices=[('EXEC', 'Executed'), ('CONF', 'Confirmed'), ('SETTLED', 'Settled'), ('CXL', 'Canceled'), ('CORR', 'Corrected')], help_text='New state.', max_length=10)),
                ('transitioned_at', models.DateTimeField(help_text='Timestamp when the transition occurred.')),
                ('reason', models.CharField(blank=True, default='', help_text="Reason (e.g., 'broker confirm received', 'settlement file matched').", max_length=120)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(help_text='Trade whose state changed.', on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='ibor.ibortradeevent')),
            ],
            options={
                'db_table': 'ibor_trd_state_hist',
            },
        ),
        migrations.DeleteModel(
            name='CashLedger',
        ),
        migrations.AddIndex(
            model_name='iborfxoverride',
            index=models.Index(fields=['currency_pair', 'rate_dt'], name='ibor_fx_ovr_currenc_53a3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfxoverride',
            index=models.Index(fields=['portfolio', 'rate_dt'], name='ibor_fx_ovr_portfol_d6711c_idx'),
        ),
        migrations.AddConstraint(
            model_name='iborfxoverride',
            constraint=models.UniqueConstraint(fields=('portfolio', 'currency_pair', 'rate_dt'), name='uq_ibor_fx_ovr_pf_pair_dt'),
        ),
        migrations.AddIndex(
            model_name='iborpricesnapshot',
            index=models.Index(fields=['security_listing', 'price_dt'], name='ibor_px_sna_securit_5de7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='iborpricesnapshot',
            index=models.Index(fields=['price_dt', 'source'], name='ibor_px_sna_price_d_f9bc81_idx'),
        ),
        migrations.AddConstraint(
            model_name='iborpricesnapshot',
            constraint=models.UniqueConstraint(fields=('security_listing', 'price_dt', 'source'), name='uq_ibor_px_snap_list_dt_src'),
        ),
        migrations.AddIndex(
            model_name='iborsourcedoc',
            index=models.Index(fields=['source_system', 'source_ref'], name='ibor_src_do_source__c5744b_idx'),
        ),
        migrations.AddIndex(
            model_name='iborsourcedoc',
            index=models.Index(fields=['file_sha256'], name='ibor_src_do_file_sh_0d2608_idx'),
        ),
        migrations.AddIndex(
            model_name='iboringestbatch',
            index=models.Index(fields=['source_system', 'created_at'], name='ibor_ing_ba_source__fe18d0_idx'),
        ),
        migrations.AddIndex(
            model_name='iborstagedtrade',
            index=models.Index(fields=['source_system', 'external_ref'], name='ibor_stg_tr_source__4f9f64_idx'),
        ),
        migrations.AddIndex(
            model_name='iborstagedtrade',
            index=models.Index(fields=['status', 'created_at'], name='ibor_stg_tr_status_fb0748_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['portfolio', 'trade_dt'], name='ibor_trd_ev_portfol_76af77_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['portfolio', 'settle_dt'], name='ibor_trd_ev_portfol_93432d_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['instrument', 'trade_dt'], name='ibor_trd_ev_instrum_fe38f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['state_cd', 'trade_dt'], name='ibor_trd_ev_state_c_870b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['source_system', 'external_ref', 'version_no'], name='ibor_trd_ev_source__fd4839_idx'),
        ),
        migrations.AddConstraint(
            model_name='ibortradeevent',
            constraint=models.UniqueConstraint(fields=('source_system', 'external_ref', 'version_no'), name='uq_ibor_trd_evt_src_ref_ver'),
        ),
        migrations.AddIndex(
            model_name='ibortaxlot',
            index=models.Index(fields=['portfolio', 'instrument', 'acquired_dt'], name='ibor_lot_in_portfol_d56e82_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortaxlot',
            index=models.Index(fields=['instrument'], name='ibor_lot_in_instrum_b2ead5_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortaxlot',
            index=models.Index(fields=['trade'], name='ibor_lot_in_trade_i_0a179e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ibortaxlot',
            constraint=models.CheckConstraint(condition=models.Q(('open_qty__gt', 0)), name='ck_lot_open_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ibortaxlot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__gte', 0)), name='ck_lot_rem_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ibortaxlot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__lte', models.F('open_qty'))), name='ck_lot_rem_le_open'),
        ),
        migrations.AddIndex(
            model_name='iborlotconsumption',
            index=models.Index(fields=['sell_trade'], name='ibor_lot_cn_sell_tr_2fc8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='iborlotconsumption',
            index=models.Index(fields=['lot'], name='ibor_lot_cn_lot_id_8e80da_idx'),
        ),
        migrations.AddConstraint(
            model_name='iborlotconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_qty__gt', 0)), name='ck_lc_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='iborlotconsumption',
            constraint=models.UniqueConstraint(fields=('sell_trade', 'lot'), name='uq_lot_cns_sell_lot'),
        ),
        migrations.AddIndex(
            model_name='iborchargecomponent',
            index=models.Index(fields=['trade'], name='ibor_chg_cm_trade_i_cabeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='iborchargecomponent',
            index=models.Index(fields=['charge_type_cd'], name='ibor_chg_cm_charge__04928e_idx'),
        ),
        migrations.AddIndex(
            model_name='iborcashevent',
            index=models.Index(fields=['portfolio', 'currency', 'effective_dt'], name='ibor_csh_ev_portfol_63f09b_idx'),
        ),
        migrations.AddIndex(
            model_name='iborcashevent',
            index=models.Index(fields=['cash_event_type', 'effective_dt'], name='ibor_csh_ev_cash_ev_c010fb_idx'),
        ),
        migrations.AddIndex(
            model_name='iborcashevent',
            index=models.Index(fields=['trade'], name='ibor_csh_ev_trade_i_96d784_idx'),
        ),
        migrations.DeleteModel(
            name='IborTrade',
        ),
        migrations.AddIndex(
            model_name='ibortradestatehistory',
            index=models.Index(fields=['trade', 'transitioned_at'], name='ibor_trd_st_trade_i_09e91f_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradestatehistory',
            index=models.Index(fields=['to_state'], name='ibor_trd_st_to_stat_a35b0c_idx'),
        ),
    ]
