# Generated by Django 5.2.10 on 2026-02-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0002_remove_ibortrade_acct_remove_ibortrade_listing_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('portfolio', '0005_alter_portfolio_port_cd_alter_portfolio_port_nm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iborchargecomponent',
            name='currency',
        ),
        migrations.AddField(
            model_name='iborchargecomponent',
            name='cost_ccy',
            field=models.ForeignKey(help_text='Charge currency ISO3 .', max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.currency'),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='account',
            field=models.ForeignKey(help_text='Account id where the trade initiate', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades_ac', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='iborcashevent',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Free text description for trade (broker label, reason, etc.).', max_length=200),
        ),
    ]
