# Generated by Django 5.2.10 on 2026-02-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0003_remove_iborchargecomponent_currency_and_more'),
        ('portfolio', '0005_alter_portfolio_port_cd_alter_portfolio_port_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibortradeevent',
            name='account',
            field=models.ForeignKey(help_text='Account id where the trade initiate', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades_ac', to='portfolio.account'),
        ),
    ]
