# Generated by Django 5.2.10 on 2026-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0004_alter_ibortradeevent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibortradeevent',
            name='book_err_txt',
            field=models.CharField(blank=True, default='', help_text='Booking error message if book_sts_cd=ERR.', max_length=400),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='book_sts_cd',
            field=models.CharField(choices=[('NEW', 'New'), ('BOK', 'Booked'), ('ERR', 'Error'), ('REV', 'Reversed')], db_index=True, default='NEW', help_text='Booking status: NEW/BOK/ERR/REV.', max_length=3),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='book_ts',
            field=models.DateTimeField(blank=True, help_text='When booking was completed (set by booking engine).', null=True),
        ),
        migrations.AlterField(
            model_name='ibortaxlot',
            name='open_qty',
            field=models.DecimalField(decimal_places=10, help_text='The original quantity that this lot was created with..', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='external_ref',
            field=models.CharField(blank=True, default='', help_text='The broker or source’s own trade identifier (voucher / contract note / execution id).', max_length=120),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='source_system',
            field=models.CharField(help_text="Where the trade come from Adapter/system identifier (e.g., 'psx_broker_x', 'sarwa', 'manual').", max_length=40),
        ),
    ]
