# Generated by Django 5.2.10 on 2026-02-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0005_ibortradeevent_book_err_txt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborlotconsumption',
            name='proceeds_amt',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Allocated net proceeds for this consumed slice (in cost_ccy).', max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='iborlotconsumption',
            name='rlzd_pnl_amt',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Realized PnL = proceeds_amt - cost_basis (in cost_ccy).', max_digits=28, null=True),
        ),
    ]
