# Generated by Django 5.2.10 on 2026-06-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0006_iborlotconsumption_proceeds_amt_and_more'),
        ('instruments', '0006_alter_issuer_issuer_code_alter_issuer_issuer_lei_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IborFeeSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('schedule_name', models.CharField(help_text='Human-friendly fee schedule name.', max_length=120)),
                ('source_system', models.CharField(blank=True, default='', help_text='Optional source system identifier.', max_length=40)),
                ('side', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='', help_text='Optional BUY/SELL filter.', max_length=4)),
                ('effective_from', models.DateField(help_text='Date from which this schedule is active.')),
                ('effective_to', models.DateField(blank=True, help_text='Optional end date.', null=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number means higher priority.')),
                ('is_default', models.BooleanField(default=False, help_text='Use as fallback schedule if nothing more specific matches.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional operations notes.')),
                ('asset_class', models.ForeignKey(blank=True, help_text='Optional asset class filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='instruments.assetclass')),
                ('asset_sub_class', models.ForeignKey(blank=True, help_text='Optional asset sub-class filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='instruments.assetsubclass')),
                ('broker', models.ForeignKey(blank=True, help_text='Optional broker-specific fee schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='masters.broker')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('exec_venue', models.ForeignKey(blank=True, help_text='Optional exchange/venue-specific fee schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='masters.exchange')),
                ('trade_ccy', models.ForeignKey(blank=True, help_text='Optional trade currency filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='masters.currency')),
            ],
            options={
                'db_table': 'ibor_fee_sch',
                'ordering': ['priority', '-effective_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IborFeeRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_at_ts', models.DateTimeField(auto_now_add=True, help_text="System timestamp when PortX recorded this row (bi-temporal 'as-at').")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp in PortX (audit).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp in PortX (audit).')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-active flag. Old versions/replaced records should be set inactive.')),
                ('sequence_no', models.PositiveIntegerField(default=10, help_text='Processing order of the rule.')),
                ('charge_type_cd', models.CharField(choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='OTHER', help_text='Normalized charge type.', max_length=10)),
                ('description', models.CharField(blank=True, default='', help_text='Display label for the fee line.', max_length=120)),
                ('calc_method', models.CharField(choices=[('PCT_GROSS', 'Percent of gross'), ('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit'), ('PCT_OF_CHARGE', 'Percent of another charge'), ('MIN_OF_PCT_OR_FLAT', 'Minimum of percent or flat'), ('MAX_OF_PCT_OR_FLAT', 'Maximum of percent or flat')], help_text='How this fee is calculated.', max_length=30)),
                ('apply_on', models.CharField(choices=[('GROSS', 'Gross amount'), ('QUANTITY', 'Quantity'), ('COMMISSION', 'Commission'), ('OTHER', 'Other')], default='GROSS', help_text='Base used for the calculation.', max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=10, help_text='Percentage rate where applicable.', max_digits=18, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=10, help_text='Flat amount where applicable.', max_digits=28, null=True)),
                ('per_unit_amount', models.DecimalField(blank=True, decimal_places=10, help_text='Per-unit/share amount where applicable.', max_digits=28, null=True)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=10, help_text='Optional minimum fee floor.', max_digits=28, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=10, help_text='Optional maximum fee cap.', max_digits=28, null=True)),
                ('reference_charge_type_cd', models.CharField(blank=True, choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='', help_text='Used when fee depends on another charge, e.g. tax on commission.', max_length=10)),
                ('rounding_dp', models.PositiveSmallIntegerField(default=4, help_text='Decimal places for rounding.')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this charge normally applies.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created/approved this record in PortX (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, help_text='Currency of calculated charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_rules', to='masters.currency')),
                ('schedule', models.ForeignKey(help_text='Parent fee schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ibor.iborfeeschedule')),
            ],
            options={
                'db_table': 'ibor_fee_rule',
                'ordering': ['schedule_id', 'sequence_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='iborfeeschedule',
            index=models.Index(fields=['broker', 'effective_from'], name='ibor_fee_sc_broker__e04abb_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfeeschedule',
            index=models.Index(fields=['exec_venue', 'effective_from'], name='ibor_fee_sc_exec_ve_8019e0_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfeeschedule',
            index=models.Index(fields=['source_system', 'effective_from'], name='ibor_fee_sc_source__061aea_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfeeschedule',
            index=models.Index(fields=['is_default'], name='ibor_fee_sc_is_defa_39b224_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfeerule',
            index=models.Index(fields=['schedule', 'sequence_no'], name='ibor_fee_ru_schedul_d05396_idx'),
        ),
        migrations.AddIndex(
            model_name='iborfeerule',
            index=models.Index(fields=['charge_type_cd'], name='ibor_fee_ru_charge__7b9315_idx'),
        ),
    ]
