# Generated by Django 5.2.10 on 2026-06-11 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0007_iborfeeschedule_iborfeerule_and_more'),
        ('instruments', '0006_alter_issuer_issuer_code_alter_issuer_issuer_lei_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('portfolio', '0005_alter_portfolio_port_cd_alter_portfolio_port_nm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iborchargecomponent',
            name='override_flag',
            field=models.BooleanField(default=False, help_text='True if ops manually changed this charge.'),
        ),
        migrations.AddField(
            model_name='iborchargecomponent',
            name='source_reference',
            field=models.CharField(blank=True, default='', help_text='Optional source row id / code.', max_length=120),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='execution_id',
            field=models.CharField(blank=True, default='', help_text='Execution/fill id from broker/OMS.', max_length=120),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='fx_override_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Optional FX override rate (trade_ccy -> settle_ccy).', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='imported_flag',
            field=models.BooleanField(default=False, help_text='True if created via import/adapter instead of manual screen.'),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='True if economics were manually overridden.'),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='order_id',
            field=models.CharField(blank=True, default='', help_text='Upstream OMS order id (if available).', max_length=120),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='order_type',
            field=models.CharField(blank=True, default='', help_text='Order type (e.g. Market, Limit).', max_length=30),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='override_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for manual override (required when manual_override=True).', max_length=250),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='settlement_cash_amount',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Cash that should move on settlement date in settle_ccy.', max_digits=28),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='total_charges',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Sum of all linked charge components (normalized into settle_ccy policy).', max_digits=28),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='trader_name',
            field=models.CharField(blank=True, default='', help_text='Trader or user who placed the order (optional).', max_length=120),
        ),
        migrations.AlterField(
            model_name='iborchargecomponent',
            name='cost_ccy',
            field=models.ForeignKey(help_text='Charge currency ISO3.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trade_charge_ccy', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='iborchargecomponent',
            name='is_withholding',
            field=models.BooleanField(default=False, help_text='True if this is withholding tax.'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='account',
            field=models.ForeignKey(help_text='Account where the trade is initiated.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades_ac', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='asset_class',
            field=models.ForeignKey(blank=True, help_text='Optional snapshot of asset class at trade time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='instruments.assetclass'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='asset_sub_class',
            field=models.ForeignKey(blank=True, help_text='Optional snapshot of asset sub‑class at trade time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='instruments.assetsubclass'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='broker',
            field=models.ForeignKey(help_text='Broker/counterparty executing or confirming the trade.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='masters.broker'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='exec_venue',
            field=models.ForeignKey(blank=True, help_text='Execution venue/exchange (PSX, NASDAQ, OTC, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='masters.exchange'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='external_ref',
            field=models.CharField(blank=True, default='', help_text='Broker/source trade id (voucher / contract note / execution id).', max_length=120),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='instrument',
            field=models.ForeignKey(help_text='Listing-level security (e.g. BOP@PSX).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='instruments.securitylisting'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='memo',
            field=models.TextField(blank=True, default='', help_text='Optional free‑text notes (ops commentary, parsing results, etc.).'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='net_amount',
            field=models.DecimalField(decimal_places=10, help_text='Net amount after charges (settlement logic).', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='portfolio',
            field=models.ForeignKey(help_text='Portfolio owning the position.', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trades', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='settle_ccy',
            field=models.ForeignKey(blank=True, help_text='Settlement currency (defaults to trade_ccy if null).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibor_settle_ccy_trades', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='source_system',
            field=models.CharField(help_text="Adapter/system identifier (e.g. 'psx_broker_x', 'sarwa', 'manual').", max_length=40),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='state_cd',
            field=models.CharField(choices=[('EXEC', 'Executed'), ('CONF', 'Confirmed'), ('SETTLED', 'Settled'), ('CXL', 'Canceled'), ('CORR', 'Corrected')], default='EXEC', help_text='Lifecycle state (EXEC/CONF/SETTLED/CXL/CORR).', max_length=10),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='state_ts',
            field=models.DateTimeField(blank=True, help_text='Timestamp when current state was achieved.', null=True),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='version_no',
            field=models.PositiveIntegerField(default=1, help_text='Version number for same external_ref (CORR creates new version).'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['broker', 'trade_dt'], name='ibor_trd_ev_broker__3caf24_idx'),
        ),
        migrations.AddIndex(
            model_name='ibortradeevent',
            index=models.Index(fields=['book_sts_cd', 'trade_dt'], name='ibor_trd_ev_book_st_bc9050_idx'),
        ),
        migrations.AddConstraint(
            model_name='iborchargecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_ibor_charge_amt_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ibortradeevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_ibor_trade_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ibortradeevent',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='ck_ibor_trade_px_gt_0'),
        ),
    ]
