# Generated by Django 5.2.10 on 2026-06-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0008_iborchargecomponent_override_flag_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibortradeevent',
            name='trade_ccy',
            field=models.ForeignKey(blank=True, help_text='Trade/contract currency (ISO3 from masters).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibor_trade_ccy_trades', to='masters.currency'),
        ),
    ]
