# Generated by Django 5.2.10 on 2026-06-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_rm_rm_nm'),
        ('ibor', '0009_alter_ibortradeevent_trade_ccy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibortradeevent',
            name='trader_name',
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='trader',
            field=models.ForeignKey(blank=True, help_text='RM / trader who placed this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_trades', to='crm.rm'),
        ),
    ]
