# Generated by Django 5.2.10 on 2026-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0010_remove_ibortradeevent_trader_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iborfeerule',
            name='calc_method',
            field=models.CharField(choices=[('PCT_GROSS', 'Percent of gross'), ('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit'), ('PCT_OF_CHARGE', 'Percent of another charge'), ('PCT_CUMUL', 'Percent of cumulative charges'), ('MIN_OF_PCT_OR_FLAT', 'Minimum of percent or flat'), ('MAX_OF_PCT_OR_FLAT', 'Maximum of percent or flat')], help_text='How this fee is calculated.', max_length=30),
        ),
    ]
