# Generated by Django 5.2.10 on 2026-06-12 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0011_alter_iborfeerule_calc_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibortradeevent',
            name='price',
            field=models.DecimalField(decimal_places=10, help_text='Trade price per unit.', max_digits=28, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='quantity',
            field=models.DecimalField(decimal_places=10, help_text='Trade quantity (supports fractional shares).', max_digits=28, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
