# Generated by Django 5.2.10 on 2026-06-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0012_alter_ibortradeevent_price_and_more'),
        ('portfolio', '0005_alter_portfolio_port_cd_alter_portfolio_port_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborcashevent',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account whose cash is impacted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibor_cash_events', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='iborfeeschedule',
            name='side',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SHORT_SELL', 'Short Sell')], default='', help_text='Optional BUY/SELL filter.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='order_type',
            field=models.CharField(blank=True, choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP', 'Stop Order'), ('STOP_LIMIT', 'Stop-Limit Order'), ('MTL', 'Market to Limit')], default='', help_text='Order type (e.g. MKT, MLT etc).', max_length=120),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='price',
            field=models.DecimalField(decimal_places=10, help_text='Trade price per unit.', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='quantity',
            field=models.DecimalField(decimal_places=10, help_text='Trade quantity (supports fractional shares).', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortradeevent',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SHORT_SELL', 'Short Sell')], help_text='BUY, SELL or Short-Sell', max_length=10),
        ),
    ]
