# Generated by Django 5.2.10 on 2026-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0013_iborcashevent_account_alter_iborfeeschedule_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborcashevent',
            name='withdrawal_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], help_text='Method of withdrawal (only for Withdrawals).', max_length=20, null=True),
        ),
    ]
