# Generated by Django 5.2.10 on 2026-06-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0014_iborcashevent_withdrawal_method'),
        ('masters', '0010_exchange_settlement_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborcashevent',
            name='currency_pair',
            field=models.ForeignKey(blank=True, help_text='FX currency pair applied for this cash event (if any).', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.currencypair'),
        ),
        migrations.AddField(
            model_name='iborcashevent',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='FX rate applied for this cash event (if any).', max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='iborfeerule',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Maximum share price for this rule to apply.', max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='iborfeerule',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Minimum share price for this rule to apply.', max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='iborcashevent',
            name='cash_event_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('TRADE_SETTLE', 'Trade settlement'), ('TRADE_FEE', 'Trade fee/charges'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('FX_CONV', 'FX conversion'), ('OTHER', 'Other')], default='OTHER', help_text='Type/category of cash movement.', max_length=20),
        ),
        migrations.AlterField(
            model_name='iborcashevent',
            name='currency',
            field=models.ForeignKey(help_text='Cash currency (ISO3 from masters).', on_delete=django.db.models.deletion.PROTECT, related_name='ibor_cash_events', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='calc_method',
            field=models.CharField(choices=[('PCT_GROSS', 'Percent of gross'), ('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit'), ('PCT_OF_CHARGE', 'Percent of another charge'), ('PCT_CUMUL', 'Percent of cumulative charges'), ('MIN_OF_PCT_OR_FLAT', 'Minimum of percent or flat'), ('MAX_OF_PCT_OR_FLAT', 'Maximum of percent or flat'), ('PSX_TIERED_COMMISSION', 'PSX Tiered Commission')], help_text='How this fee is calculated.', max_length=30),
        ),
    ]
