# Generated by Django 5.2.10 on 2026-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0015_iborcashevent_currency_pair_iborcashevent_fx_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iborlotconsumption',
            name='consumed_qty',
            field=models.DecimalField(decimal_places=4, help_text='Quantity consumed from this lot (FIFO).', max_digits=28),
        ),
        migrations.AlterField(
            model_name='iborlotconsumption',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, help_text='Total cost basis consumed = consumed_qty * unit_cost.', max_digits=28),
        ),
        migrations.AlterField(
            model_name='iborlotconsumption',
            name='proceeds_amt',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Allocated net proceeds for this consumed slice (in cost_ccy).', max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='iborlotconsumption',
            name='rlzd_pnl_amt',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Realized PnL = proceeds_amt - cost_basis (in cost_ccy).', max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='iborlotconsumption',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, help_text='Unit cost used for this consumption (copied from lot at time of consumption).', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortaxlot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this lot is active. Set to False if cancelled or fully reversed.'),
        ),
        migrations.AlterField(
            model_name='ibortaxlot',
            name='open_qty',
            field=models.DecimalField(decimal_places=4, help_text='The original quantity that this lot was created with..', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortaxlot',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=4, help_text='Remaining lot quantity after FIFO consumptions.', max_digits=28),
        ),
        migrations.AlterField(
            model_name='ibortaxlot',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, help_text='Unit cost including allocated charges (in cost_ccy).', max_digits=28),
        ),
    ]
