# Generated by Django 5.2.10 on 2026-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0016_alter_iborlotconsumption_consumed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibortradeevent',
            name='discretion_enabled',
            field=models.BooleanField(default=False, help_text='True if discretion is allowed for this trade.'),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='trading_enabled',
            field=models.BooleanField(default=True, help_text='True if trading is enabled for this trade.'),
        ),
    ]
