# Generated by Django 5.2.10 on 2026-06-14 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0017_ibortradeevent_discretion_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ibortradeevent',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated this trade event.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ibortradeevent',
            name='pm_discretion_used',
            field=models.BooleanField(default=False, help_text='Ticked when the PM is exercising discretion on this specific trade.'),
        ),
    ]
