# Generated by Django 5.2.10 on 2026-06-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0018_ibortradeevent_initiated_by_and_more'),
        ('masters', '0011_broker_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iborfeerule',
            name='calc_method',
            field=models.CharField(choices=[('PCT_GROSS', 'Percent of gross'), ('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit'), ('PCT_OF_CHARGE', 'Percent of another charge'), ('PCT_CUMUL', 'Percent of cumulative charges'), ('MIN_OF_PCT_OR_FLAT', 'Minimum of percent or flat'), ('MAX_OF_PCT_OR_FLAT', 'Maximum of percent or flat'), ('PSX_TIERED_COMMISSION', 'PSX Tiered Commission')], help_text='How this fee is calculated (Gross, Per Unit etc.).', max_length=30),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='charge_type_cd',
            field=models.CharField(choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='COMM', help_text='Normalized charge type.', max_length=10),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Commission Currency of calculated charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_rules', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Charges description for trading.', max_length=120),
        ),
        migrations.DeleteModel(
            name='PositionLot',
        ),
    ]
