# Generated by Django 5.2.10 on 2026-06-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0019_alter_iborfeerule_calc_method_and_more'),
        ('instruments', '0006_alter_issuer_issuer_code_alter_issuer_issuer_lei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iborfeerule',
            name='reference_charge_type_cd',
            field=models.CharField(blank=True, choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='', help_text='Referenced charge code(s), e.g. COMM or COMM,CDC for cumulative tax.', max_length=100),
        ),
        migrations.AlterField(
            model_name='iborfeeschedule',
            name='asset_class',
            field=models.ForeignKey(blank=True, help_text='The Schedule for which asset class (Equity, FI, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='instruments.assetclass'),
        ),
        migrations.AlterField(
            model_name='iborfeeschedule',
            name='schedule_name',
            field=models.CharField(help_text='Broker fee schedule name. (SCS One Account For All)', max_length=120),
        ),
    ]
