# Generated by Django 5.2.10 on 2026-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibor', '0020_alter_iborfeerule_reference_charge_type_cd_and_more'),
        ('instruments', '0006_alter_issuer_issuer_code_alter_issuer_issuer_lei_and_more'),
        ('masters', '0011_broker_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborfeerule',
            name='alternate_amount_basis',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit amount')], default='', help_text='For MIN/MAX comparison methods: whether alternate amount is FLAT or PER_UNIT.', max_length=20),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='apply_on',
            field=models.CharField(choices=[('GROSS', 'Gross amount'), ('QUANTITY', 'Quantity'), ('COMMISSION', 'Commission'), ('OTHER', 'Other')], default='GROSS', help_text='Base used for the percentage leg of the calculation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='calc_method',
            field=models.CharField(choices=[('PCT_GROSS', 'Percent of gross'), ('FLAT', 'Flat amount'), ('PER_UNIT', 'Per unit'), ('PCT_OF_CHARGE', 'Percent of another charge'), ('PCT_CUMULATIVE', 'Percent of cumulative charges'), ('MIN_OF_PCT_OR_ALT', 'Lesser of percent or alternate amount'), ('MAX_OF_PCT_OR_ALT', 'Greater of percent or alternate amount')], help_text='How this fee is calculated.', max_length=30),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='charge_type_cd',
            field=models.CharField(choices=[('COMM', 'Commission'), ('TAX', 'Tax'), ('LEVY', 'Levy/Fee'), ('VAT', 'VAT/GST/SST'), ('STAMP', 'Stamp duty'), ('OTHER', 'Other')], default='OTHER', help_text='Normalized charge type.', max_length=10),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency of calculated charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_rules', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Display label for the fee line.', max_length=120),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='flat_amount',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Flat amount per order where applicable.', max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='per_unit_amount',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Per-unit/share/contract amount where applicable.', max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Percentage rate where applicable, e.g. 0.0015 for 0.15%.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='iborfeerule',
            name='reference_charge_type_cd',
            field=models.CharField(blank=True, default='', help_text='Referenced charge code(s), e.g. COMM or COMM,CDC for cumulative tax.', max_length=100),
        ),
        migrations.AlterField(
            model_name='iborfeeschedule',
            name='asset_class',
            field=models.ForeignKey(blank=True, help_text='Optional asset class filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ibor_fee_schedules', to='instruments.assetclass'),
        ),
        migrations.AlterField(
            model_name='iborfeeschedule',
            name='schedule_name',
            field=models.CharField(help_text='Human-friendly fee schedule name.', max_length=120),
        ),
    ]
