# Generated by Django 5.2.10 on 2026-01-26 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('investor_friendly', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('numeric_code', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ref_currency',
                'ordering': ['currency_id'],
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_type', models.CharField(choices=[('Index', 'Index'), ('Blend', 'Blend'), ('Absolute', 'Absolute'), ('Custom', 'Custom')], default='Index', max_length=20)),
                ('benchmark_name', models.CharField(max_length=120, unique=True)),
                ('ticker', models.CharField(blank=True, max_length=40, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3, null=True)),
                ('provider', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=20)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benchmark',
                'indexes': [models.Index(fields=['status', 'currency'], name='benchmark_status_f3041e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exchange_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exchange_name', models.CharField(max_length=100)),
                ('exchange_code', models.CharField(max_length=20)),
                ('mic', models.CharField(blank=True, max_length=4, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('market_status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges', to='masters.country')),
                ('exchange_currency', models.ForeignKey(blank=True, db_column='code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges', to='masters.currency', to_field='code')),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=120, unique=True)),
                ('mgmt_fee_bps', models.PositiveIntegerField()),
                ('billing_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi Annually'), ('annually', 'Annually'), ('one_time', 'One Time')], default='quarterly')),
                ('aum_measurement', models.CharField(choices=[('end_of_period_AUM', 'End of Period AUM'), ('average_daily_AUM', 'Average Daily AUM'), ('average_monthly_AUM', 'Average Monthly AUM'), ('average_quarterly_AUM', 'Average Quarterly AUM')], default='average_daily_AUM', max_length=30)),
                ('tiering_flag', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('draft', 'Draft')], default='active', max_length=10)),
                ('performance_fee_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('effective_date', models.DateField()),
                ('billing_timing', models.CharField(choices=[('in_advance', 'In Advance'), ('in_arrears', 'In Arrears')], default='in_arrears', max_length=20)),
                ('day_count_convention', models.CharField(choices=[('actual_360', 'Actual/360'), ('actual_365', 'Actual/365'), ('30_360', '30/360'), ('30_365', '30/365'), ('actual_actual', 'Actual/Actual')], default='actual_360', max_length=15)),
                ('fee_inclusive_of_tax', models.BooleanField(default=False)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('min_fee_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('max_fee_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fee_schedule',
                'indexes': [models.Index(fields=['status', 'effective_date'], name='fee_schedul_status_1e6aaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_code', models.CharField(max_length=30, unique=True)),
                ('broker_name', models.CharField(max_length=200)),
                ('broker_type', models.CharField(choices=[('BRK', 'Broker'), ('CUS', 'Custodian'), ('PLT', 'Platform'), ('BNK', 'Bank')], default='BRK', max_length=3)),
                ('default_base_currency', models.CharField(default='USD', max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('regulator', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='masters.country')),
            ],
            options={
                'db_table': 'broker',
                'indexes': [models.Index(fields=['broker_code'], name='broker_broker__fe1221_idx'), models.Index(fields=['status', 'broker_type'], name='broker_status_aae1c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('currency_pair_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(db_column='base_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_base', to='masters.currency')),
                ('quote_currency', models.ForeignKey(db_column='quote_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='pairs_as_quote', to='masters.currency')),
            ],
            options={
                'db_table': 'currency_pair',
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency'), name='uq_currency_pair_base_quote'), models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='ck_currency_pair_base_ne_quote')],
            },
        ),
        migrations.CreateModel(
            name='FxRateDaily',
            fields=[
                ('fx_rate_daily_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate_date', models.DateField()),
                ('mid', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.TextField(blank=True, null=True)),
                ('source_series', models.TextField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(db_column='base_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_as_base', to='masters.currency')),
                ('quote_currency', models.ForeignKey(db_column='quote_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_as_quote', to='masters.currency')),
            ],
            options={
                'db_table': 'fx',
                'indexes': [models.Index(fields=['rate_date'], name='fx_rate_da_4bdc50_idx'), models.Index(fields=['base_currency', 'quote_currency', 'rate_date'], name='fx_base_cu_ffe1ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('rate_date', 'base_currency', 'quote_currency', 'source_series'), name='uq_fx_rate_daily_pair_date_series')],
            },
        ),
    ]
