# Generated by Django 5.2.10 on 2026-01-26 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GicsEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ref_gics_edition',
                'indexes': [models.Index(fields=['is_current', 'effective_date'], name='ref_gics_ed_is_curr_525572_idx')],
            },
        ),
        migrations.CreateModel(
            name='GicsIndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', "GICS industry group code must be 4 digits (e.g., '1010').")])),
                ('name', models.CharField(max_length=150)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_groups', to='taxonomy.gicsedition')),
            ],
            options={
                'db_table': 'ref_gics_industry_group',
                'ordering': ['edition_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GicsIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', "GICS industry code must be 6 digits (e.g., '101020').")])),
                ('name', models.CharField(max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='taxonomy.gicsedition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industries', to='taxonomy.gicsindustrygroup')),
            ],
            options={
                'db_table': 'ref_gics_industry',
                'ordering': ['edition_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GicsSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', "GICS sector code must be 2 digits (e.g., '10').")])),
                ('name', models.CharField(max_length=100)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='taxonomy.gicsedition')),
            ],
            options={
                'db_table': 'ref_gics_sector',
                'ordering': ['edition_id', 'code'],
            },
        ),
        migrations.AddField(
            model_name='gicsindustrygroup',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_groups', to='taxonomy.gicssector'),
        ),
        migrations.CreateModel(
            name='GicsSubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', "GICS subindustry code must be 8 digits (e.g., '10102010').")])),
                ('name', models.CharField(max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subindustries', to='taxonomy.gicsedition')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subindustries', to='taxonomy.gicsindustry')),
            ],
            options={
                'db_table': 'ref_gics_subindustry',
                'ordering': ['edition_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LocalSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_sectors', to='masters.exchange')),
            ],
            options={
                'db_table': 'ref_local_sector',
                'ordering': ['exchange_id', 'local_code'],
            },
        ),
        migrations.CreateModel(
            name='LocalSectorGicsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_sector_maps', to='taxonomy.gicsedition')),
                ('gics_subindustry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_maps', to='taxonomy.gicssubindustry')),
                ('local_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gics_maps', to='taxonomy.localsector')),
            ],
            options={
                'db_table': 'map_local_sector_gics',
            },
        ),
        migrations.AddIndex(
            model_name='gicsindustry',
            index=models.Index(fields=['edition', 'code'], name='ref_gics_in_edition_498ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='gicsindustry',
            index=models.Index(fields=['group'], name='ref_gics_in_group_i_b20c85_idx'),
        ),
        migrations.AddConstraint(
            model_name='gicsindustry',
            constraint=models.UniqueConstraint(fields=('edition', 'code'), name='uq_gics_industry_edition_code'),
        ),
        migrations.AddIndex(
            model_name='gicssector',
            index=models.Index(fields=['edition', 'code'], name='ref_gics_se_edition_c277a8_idx'),
        ),
        migrations.AddIndex(
            model_name='gicssector',
            index=models.Index(fields=['code'], name='ref_gics_se_code_7cffd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='gicssector',
            constraint=models.UniqueConstraint(fields=('edition', 'code'), name='uq_gics_sector_edition_code'),
        ),
        migrations.AddIndex(
            model_name='gicsindustrygroup',
            index=models.Index(fields=['edition', 'code'], name='ref_gics_in_edition_addd11_idx'),
        ),
        migrations.AddIndex(
            model_name='gicsindustrygroup',
            index=models.Index(fields=['sector'], name='ref_gics_in_sector__85dbd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='gicsindustrygroup',
            constraint=models.UniqueConstraint(fields=('edition', 'code'), name='uq_gics_group_edition_code'),
        ),
        migrations.AddIndex(
            model_name='gicssubindustry',
            index=models.Index(fields=['edition', 'code'], name='ref_gics_su_edition_b44ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='gicssubindustry',
            index=models.Index(fields=['industry'], name='ref_gics_su_industr_7e9386_idx'),
        ),
        migrations.AddConstraint(
            model_name='gicssubindustry',
            constraint=models.UniqueConstraint(fields=('edition', 'code'), name='uq_gics_subindustry_edition_code'),
        ),
        migrations.AddIndex(
            model_name='localsector',
            index=models.Index(fields=['exchange', 'local_code'], name='ref_local_s_exchang_0010a9_idx'),
        ),
        migrations.AddIndex(
            model_name='localsector',
            index=models.Index(fields=['name'], name='ref_local_s_name_f37214_idx'),
        ),
        migrations.AddConstraint(
            model_name='localsector',
            constraint=models.UniqueConstraint(fields=('exchange', 'local_code'), name='uq_local_sector_exchange_code'),
        ),
        migrations.AddIndex(
            model_name='localsectorgicsmap',
            index=models.Index(fields=['edition', 'local_sector'], name='map_local_s_edition_f1013a_idx'),
        ),
        migrations.AddIndex(
            model_name='localsectorgicsmap',
            index=models.Index(fields=['gics_subindustry'], name='map_local_s_gics_su_05658f_idx'),
        ),
        migrations.AddConstraint(
            model_name='localsectorgicsmap',
            constraint=models.UniqueConstraint(fields=('edition', 'local_sector'), name='uq_local_sector_map_edition_sector'),
        ),
    ]
