# Generated by Django 5.2.10 on 2026-01-26 19:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_class_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('asset_class_name', models.CharField(max_length=64)),
                ('asset_class_description', models.TextField(blank=True, default='')),
                ('risk_bucket', models.CharField(choices=[('LOW', 'Low'), ('LOW_MED', 'Low/Medium'), ('MED', 'Medium'), ('HIGH', 'High'), ('VAR', 'Variable')], max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.IntegerField(default=101)),
            ],
            options={
                'verbose_name': 'Asset Class',
                'verbose_name_plural': 'Asset Classes',
                'db_table': 'ref_asset_class',
                'ordering': ['sort_order', 'asset_class_code'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='ref_asset_c_is_acti_c64fc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetSubClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_asset_class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_asset_class_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('sub_asset_class_description', models.CharField(max_length=255)),
                ('terms_family', models.CharField(choices=[('CASH', 'Cash'), ('EQUITY', 'Equity'), ('FI', 'Fixed Income'), ('FUND', 'Fund/Collective'), ('FX', 'FX'), ('DERIV', 'Derivative'), ('CRYPTO', 'Crypto'), ('CMDTY', 'Commodity'), ('RE', 'Real Estate'), ('NONE', 'None')], max_length=16)),
                ('supports_fractional', models.BooleanField(default=False)),
                ('income_type', models.CharField(choices=[('NONE', 'None'), ('DIVIDEND', 'Dividend'), ('COUPON', 'Coupon/Profit'), ('DISTRIBUTION', 'Distribution')], default='NONE', max_length=16)),
                ('requires_coupon', models.BooleanField(default=False)),
                ('requires_maturity', models.BooleanField(default=False)),
                ('requires_underlying', models.BooleanField(default=False)),
                ('is_collective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.IntegerField(default=101)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_classes', to='instruments.assetclass')),
            ],
            options={
                'verbose_name': 'Asset Sub Class',
                'verbose_name_plural': 'Asset Sub Classes',
                'db_table': 'ref_asset_sub_class',
                'ordering': ['asset_class__sort_order', 'sort_order', 'sub_asset_class_code'],
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('issuer_type', models.CharField(choices=[('COMPANY', 'Company'), ('SOVEREIGN', 'Sovereign'), ('FUND', 'Fund/Asset Manager'), ('BANK', 'Bank'), ('SPV', 'SPV/Trust'), ('OTHER', 'Other')], default='COMPANY', max_length=16)),
                ('headquarters_city', models.CharField(blank=True, default='', max_length=128)),
                ('issuer_lei', models.CharField(blank=True, db_index=True, default='', help_text='LEI (if available). Should be unique when present.', max_length=32)),
                ('fiscal_year_end_month', models.PositiveSmallIntegerField(blank=True, help_text='Issuer fiscal year end month (1-12).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('website', models.URLField(blank=True, default='')),
                ('issuer_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_by', models.IntegerField(default=101)),
                ('country', models.ForeignKey(help_text='Domicile/registered country.py of the issuer.', on_delete=django.db.models.deletion.PROTECT, related_name='issuers', to='masters.country')),
                ('gics_sector', models.ForeignKey(blank=True, help_text='GICS sector mapping (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuers', to='taxonomy.gicssector')),
                ('parent_issuer', models.ForeignKey(blank=True, help_text='Parent issuer/legal entity (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='instruments.issuer')),
            ],
            options={
                'verbose_name': 'Issuer',
                'verbose_name_plural': 'Issuers',
                'db_table': 'ref_issuer',
                'ordering': ['issuer_name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_listing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, help_text='Venue-specific ticker/symbol (e.g., PIBTL, IVV, 7010.SR).', max_length=32, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\.\\-_]+$', 'Ticker contains invalid characters.')])),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary listing used by default for UI/reporting (one per security ideally).')),
                ('venue_type', models.CharField(choices=[('EXCHANGE', 'Exchange'), ('OTC', 'OTC'), ('PLATFORM', 'Platform'), ('INTERNAL', 'Internal')], default='EXCHANGE', max_length=16)),
                ('board_segment', models.CharField(blank=True, default='', help_text='Board/segment (e.g., Main Board, OTCQX, etc.).', max_length=64)),
                ('effective_from', models.DateField(blank=True, help_text='Start date when this ticker/venue mapping became valid.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='End date when this listing ceased to be valid (delist/rename).', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELISTED', 'Delisted')], db_index=True, default='ACTIVE', max_length=16)),
                ('trading_enabled', models.BooleanField(db_index=True, default=True, help_text='If false, block new trades for this listing (compliance/ops control).')),
                ('created_by', models.IntegerField(default=101)),
                ('exchange', models.ForeignKey(blank=True, help_text='Trading venue exchange.py (nullable for OTC/platform lines).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_listings', to='masters.exchange')),
                ('price_currency', models.ForeignKey(help_text='Currency in which this listing is traded/quoted.', on_delete=django.db.models.deletion.PROTECT, related_name='listing_price_currencies', to='masters.currency')),
            ],
            options={
                'verbose_name': 'Security Listing',
                'verbose_name_plural': 'Security Listings',
                'db_table': 'sec_security_listing',
                'ordering': ['security_id', '-is_primary', 'ticker'],
            },
        ),
        migrations.CreateModel(
            name='SecurityMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('security_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable UUID for integrations (does not change).', unique=True)),
                ('security_name', models.CharField(help_text="Instrument display name (e.g., 'Pakistan International Bulk Transportation - Ordinary Share').", max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_by', models.IntegerField(default=101)),
                ('base_currency', models.ForeignKey(help_text='Economic/base currency (used for reporting/valuation conventions).', on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_securities', to='masters.currency')),
                ('domicile_country', models.ForeignKey(blank=True, help_text='Instrument domicile/registration country.py (nullable; often same as issuer country.py).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiciled_securities', to='masters.country')),
                ('issuer', models.ForeignKey(help_text='Issuer/legal entity that issued this instrument.', on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='instruments.issuer')),
                ('primary_listing', models.ForeignKey(blank=True, help_text='Optional convenience link to the primary listing row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_securities', to='instruments.securitylisting')),
                ('sub_class', models.ForeignKey(help_text='Sub-asset class controlling terms family and validation flags.', on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='instruments.assetsubclass')),
            ],
            options={
                'verbose_name': 'Security Master',
                'verbose_name_plural': 'Security Master',
                'db_table': 'sec_security_master',
                'ordering': ['security_name'],
            },
        ),
        migrations.AddField(
            model_name='securitylisting',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='instruments.securitymaster'),
        ),
        migrations.CreateModel(
            name='SecurityIdentifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_identifier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('ISIN', 'ISIN'), ('CUSIP', 'CUSIP'), ('SEDOL', 'SEDOL'), ('FIGI', 'FIGI'), ('RIC', 'RIC (Refinitiv/Reuters)'), ('BBGID', 'Bloomberg Global ID'), ('TICKER', 'Ticker (venue-specific)'), ('LOCAL_CODE', 'Local Exchange Code'), ('FUND_TICKER', 'Fund Ticker')], db_index=True, max_length=24)),
                ('id_value', models.CharField(db_index=True, max_length=128)),
                ('source_vendor', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateField(blank=True, help_text='When this identifier was verified/confirmed (manual or vendor).', null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary identifier of this type for the security.')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_by', models.IntegerField(default=101)),
                ('listing', models.ForeignKey(blank=True, help_text='Optional: link identifier to a specific listing (RIC often listing-level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifiers', to='instruments.securitylisting')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='instruments.securitymaster')),
            ],
            options={
                'verbose_name': 'Security Identifier',
                'verbose_name_plural': 'Security Identifiers',
                'db_table': 'sec_security_identifier',
                'ordering': ['security_id', 'id_type', 'id_value'],
            },
        ),
        migrations.AddIndex(
            model_name='assetsubclass',
            index=models.Index(fields=['asset_class', 'is_active', 'sort_order'], name='ref_asset_s_asset_c_ceb73b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsubclass',
            index=models.Index(fields=['terms_family', 'is_active'], name='ref_asset_s_terms_f_8eec34_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetsubclass',
            constraint=models.UniqueConstraint(fields=('asset_class', 'sort_order'), name='uq_asset_sub_class_asset_class_sort_order'),
        ),
        migrations.AddIndex(
            model_name='issuer',
            index=models.Index(fields=['issuer_status', 'issuer_type'], name='ref_issuer_issuer__b6e751_idx'),
        ),
        migrations.AddIndex(
            model_name='issuer',
            index=models.Index(fields=['country', 'issuer_status'], name='ref_issuer_country_54be92_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuer',
            constraint=models.UniqueConstraint(condition=models.Q(('issuer_lei', ''), _negated=True), fields=('issuer_lei',), name='uq_issuer_lei_nonempty'),
        ),
        migrations.AddIndex(
            model_name='securitymaster',
            index=models.Index(fields=['status', 'issuer'], name='sec_securit_status_fda7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='securitymaster',
            index=models.Index(fields=['status', 'sub_class'], name='sec_securit_status_b75746_idx'),
        ),
        migrations.AddConstraint(
            model_name='securitymaster',
            constraint=models.UniqueConstraint(fields=('issuer', 'sub_class', 'security_name'), name='uq_security_master_issuer_subclass_name'),
        ),
        migrations.AddIndex(
            model_name='securitylisting',
            index=models.Index(fields=['ticker', 'status'], name='sec_securit_ticker_3d2cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylisting',
            index=models.Index(fields=['security', 'is_primary', 'status'], name='sec_securit_securit_056158_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylisting',
            index=models.Index(fields=['exchange', 'ticker'], name='sec_securit_exchang_240ea9_idx'),
        ),
        migrations.AddConstraint(
            model_name='securitylisting',
            constraint=models.UniqueConstraint(fields=('security', 'exchange', 'ticker'), name='uq_listing_security_exchange_ticker'),
        ),
        migrations.AddConstraint(
            model_name='securitylisting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('security',), name='uq_listing_one_primary_per_security'),
        ),
        migrations.AddIndex(
            model_name='securityidentifier',
            index=models.Index(fields=['id_type', 'id_value'], name='sec_securit_id_type_68336a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityidentifier',
            index=models.Index(fields=['security', 'id_type', 'status'], name='sec_securit_securit_55a438_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityidentifier',
            constraint=models.UniqueConstraint(fields=('id_type', 'id_value'), name='uq_identifier_type_value'),
        ),
        migrations.AddConstraint(
            model_name='securityidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('security', 'id_type'), name='uq_identifier_one_primary_per_security_type'),
        ),
    ]
