# Generated by Django 5.2.10 on 2026-02-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylisting',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='instruments.securitymaster'),
        ),
    ]
