# Generated by Django 5.2.10 on 2026-02-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_securitylisting_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymaster',
            name='primary_listing',
        ),
    ]
