# Generated by Django 5.2.10 on 2026-02-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_remove_securitymaster_primary_listing'),
        ('taxonomy', '0003_alter_localsectorgicsmap_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='gics_sector',
        ),
        migrations.AddField(
            model_name='issuer',
            name='local_sector',
            field=models.ForeignKey(blank=True, help_text=' Local sector classification (source: PSX).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuers', to='taxonomy.localsector'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='asset_class_code',
            field=models.CharField(db_index=True, help_text='Asset class code e.g. FI', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='asset_class_description',
            field=models.TextField(blank=True, default='', help_text='Short institutional description'),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='asset_class_name',
            field=models.CharField(help_text='Asset class name e.g. Fixed Income', max_length=64),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='risk_bucket',
            field=models.CharField(choices=[('LOW', 'Low'), ('LOW_MED', 'Low/Medium'), ('MED', 'Medium'), ('HIGH', 'High'), ('VAR', 'Variable')], help_text='Risk bucket e.g. Low/High', max_length=16),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sort order for better UI'),
        ),
        migrations.AlterField(
            model_name='assetsubclass',
            name='asset_class',
            field=models.ForeignKey(help_text='Asset Code(FK) from asset table', on_delete=django.db.models.deletion.PROTECT, related_name='sub_classes', to='instruments.assetclass'),
        ),
        migrations.AlterField(
            model_name='assetsubclass',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='UI convention'),
        ),
        migrations.AlterField(
            model_name='assetsubclass',
            name='sub_asset_class_code',
            field=models.CharField(db_index=True, help_text='Sub Asset Class Code e.g. EQ_COMMON', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='assetsubclass',
            name='sub_asset_class_description',
            field=models.CharField(help_text='Sub Asset Class Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsubclass',
            name='supports_fractional',
            field=models.BooleanField(default=False, help_text='Supports Fractional trading like in decimals like ETH'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='headquarters_city',
            field=models.CharField(blank=True, default='', help_text='City of the headquarters.', max_length=128),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='issuer_code',
            field=models.CharField(db_index=True, help_text='Security Issuer organization Code e.g. PIBTL', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='issuer_id',
            field=models.BigAutoField(help_text='Security Issuer organization ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='issuer_name',
            field=models.CharField(help_text='Security Issuer organization Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Website of the issuer (optional).'),
        ),
        migrations.AlterField(
            model_name='securitylisting',
            name='security',
            field=models.ForeignKey(help_text='Issuer ID e.g. PIBTL', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='instruments.securitymaster'),
        ),
        migrations.AlterField(
            model_name='securitylisting',
            name='security_listing_id',
            field=models.BigAutoField(help_text='ID', primary_key=True, serialize=False),
        ),
    ]
