# Generated by Django 5.2.10 on 2026-02-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_remove_issuer_gics_sector_issuer_local_sector_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('taxonomy', '0003_alter_localsectorgicsmap_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymaster',
            name='gics_sub_industry',
            field=models.ForeignKey(blank=True, help_text='GICS sub-industry classification (security-level override; defaults from issuer mapping).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='securities', to='taxonomy.gicssubindustry'),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='domicile_country',
            field=models.ForeignKey(blank=True, help_text='Instrument domicile/registration country (nullable; often same as issuer country).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiciled_securities', to='masters.country'),
        ),
        migrations.AlterField(
            model_name='securitymaster',
            name='security_name',
            field=models.CharField(help_text="Instrument display name (e.g.,'Pakistan International Bulk Transportation - Ordinary Share').", max_length=255),
        ),
    ]
