# Generated by Django 5.2.10 on 2026-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_securitymaster_gics_sub_industry_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('taxonomy', '0003_alter_localsectorgicsmap_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='issuer_code',
            field=models.CharField(db_index=True, help_text='Internally generated code for the issuer e.e.ISS_PK_00000123.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='issuer_lei',
            field=models.CharField(blank=True, db_index=True, default='', help_text='LEI (if available). Should be unique when present.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='issuer',
            index=models.Index(fields=['country', 'local_sector', 'issuer_status'], name='ref_issuer_country_dcd6cd_idx'),
        ),
    ]
