# Generated by Django 5.2.10 on 2026-02-01 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('mandate_id', models.BigAutoField(db_column='mand_id', primary_key=True, serialize=False)),
                ('mandate_name', models.CharField(db_column='mand_nm', max_length=140)),
                ('base_ccy', models.CharField(db_column='base_ccy', default='USD', max_length=3)),
                ('authority', models.CharField(choices=[('DIS', 'Discretionary'), ('ADV', 'Advisory'), ('MOD', 'Model-only'), ('SIG', 'Signal-only')], db_column='auth_cd', max_length=3)),
                ('approval_mode', models.CharField(choices=[('PRE', 'Pre-trade approval'), ('PST', 'Post-trade acknowledgement'), ('NON', 'None')], db_column='aprv_md_cd', default='PRE', max_length=3)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], db_column='sts_cd', default='ACT', max_length=3)),
                ('inception_dt', models.DateField(db_column='incp_dt', default=django.utils.timezone.localdate)),
                ('termination_dt', models.DateField(blank=True, db_column='term_dt', null=True)),
                ('reporting_frequency', models.CharField(blank=True, db_column='rpt_freq', max_length=20, null=True)),
                ('reporting_delivery', models.CharField(blank=True, db_column='rpt_dlvr', max_length=20, null=True)),
                ('created_by', models.IntegerField(db_column='crt_by', default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_ts')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='upd_ts')),
                ('benchmark', models.ForeignKey(blank=True, db_column='bmk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='masters.benchmark')),
                ('fee_schedule', models.ForeignKey(blank=True, db_column='fee_sched_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='masters.feeschedule')),
                ('investor', models.ForeignKey(db_column='inv_id', on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='crm.investor')),
                ('rm', models.ForeignKey(blank=True, db_column='rm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='crm.rm')),
            ],
            options={
                'db_table': 'px_mand_hdr',
            },
        ),
        migrations.CreateModel(
            name='IPS',
            fields=[
                ('ips_id', models.BigAutoField(db_column='ips_id', primary_key=True, serialize=False)),
                ('ips_name', models.CharField(db_column='ips_nm', max_length=140)),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('ACT', 'Active'), ('INA', 'Inactive')], db_column='sts_cd', default='DRF', max_length=3)),
                ('risk_profile', models.CharField(choices=[('CON', 'Conservative'), ('MOD', 'Moderate'), ('AGR', 'Aggressive')], db_column='risk_prf_cd', max_length=3)),
                ('investment_objective', models.CharField(choices=[('PRES', 'Capital Preservation'), ('INCM', 'Income'), ('GRTH', 'Growth'), ('TRTN', 'Total Return')], db_column='inv_obj_cd', max_length=4)),
                ('time_horizon', models.CharField(choices=[('S', 'Short'), ('M', 'Medium'), ('L', 'Long')], db_column='tm_hzn_cd', max_length=1)),
                ('liquidity_needs', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIG', 'High')], db_column='liq_need_cd', max_length=3)),
                ('effective_start_dt', models.DateField(db_column='eff_start_dt', default=django.utils.timezone.localdate)),
                ('effective_end_dt', models.DateField(blank=True, db_column='eff_end_dt', null=True)),
                ('review_frequency', models.CharField(blank=True, choices=[('MON', 'Monthly'), ('QTR', 'Quarterly'), ('SAA', 'Semi-Annual'), ('ANN', 'Annual'), ('ADH', 'Ad hoc')], db_column='rvw_freq_cd', max_length=3, null=True)),
                ('next_review_due', models.DateField(blank=True, db_column='nxt_rvw_due_dt', null=True)),
                ('is_current', models.BooleanField(db_column='is_curr', default=True)),
                ('created_by', models.IntegerField(db_column='crt_by', default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_ts')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='upd_ts')),
                ('portfolio', models.ForeignKey(blank=True, db_column='port_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips_overrides', to='portfolio.portfolio')),
                ('mandate', models.ForeignKey(db_column='mand_id', on_delete=django.db.models.deletion.PROTECT, related_name='ips_versions', to='policies.mandate')),
            ],
            options={
                'db_table': 'px_ips_hdr',
            },
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['investor', 'status'], name='ix_mand_inv_sts'),
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['authority', 'status'], name='ix_mand_auth_sts'),
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(('termination_dt__isnull', True), ('termination_dt__gt', models.F('inception_dt')), _connector='OR'), name='ck_mand_dt_range'),
        ),
        migrations.AddIndex(
            model_name='ips',
            index=models.Index(fields=['mandate', 'is_current'], name='ix_ips_mand_curr'),
        ),
        migrations.AddIndex(
            model_name='ips',
            index=models.Index(fields=['portfolio', 'is_current'], name='ix_ips_port_curr'),
        ),
        migrations.AddIndex(
            model_name='ips',
            index=models.Index(fields=['status'], name='ix_ips_sts'),
        ),
        migrations.AddConstraint(
            model_name='ips',
            constraint=models.CheckConstraint(condition=models.Q(('effective_end_dt__isnull', True), ('effective_end_dt__gt', models.F('effective_start_dt')), _connector='OR'), name='ck_ips_eff_dt_range'),
        ),
        migrations.AddConstraint(
            model_name='ips',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('portfolio__isnull', True)), fields=('mandate',), name='uq_ips_one_curr_per_mand'),
        ),
        migrations.AddConstraint(
            model_name='ips',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('portfolio__isnull', False)), fields=('portfolio',), name='uq_ips_one_curr_per_port'),
        ),
    ]
