# Generated by Django 5.2.10 on 2026-02-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='base_ccy',
            field=models.ForeignKey(db_column='base_ccy_id', default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='masters.currency'),
        ),
    ]
