# Generated by Django 5.2.10 on 2026-02-09 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_investor_investor_investo_86c487_idx_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('policies', '0002_alter_mandate_base_ccy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSVersion',
            fields=[
                ('ips_ver_id', models.BigAutoField(db_column='ips_ver_id', help_text='IPS version key, e.g. 9001', primary_key=True, serialize=False)),
                ('ver_no', models.PositiveIntegerField(db_column='ver_no', help_text='Version number, e.g. 1')),
                ('ips_nm', models.CharField(db_column='ips_nm', help_text='IPS name, e.g. Balanced IPS v1', max_length=140)),
                ('sts_cd', models.CharField(choices=[('DRF', 'Draft'), ('ACT', 'Active'), ('SUP', 'Superseded'), ('INA', 'Inactive')], db_column='sts_cd', default='DRF', help_text='Status, e.g. DRF', max_length=3)),
                ('risk_prf_cd', models.CharField(choices=[('CON', 'Conservative'), ('MOD', 'Moderate'), ('AGR', 'Aggressive')], db_column='risk_prf_cd', help_text='Risk profile, e.g. MOD', max_length=3)),
                ('inv_obj_cd', models.CharField(choices=[('PRES', 'Capital Preservation'), ('INCM', 'Income'), ('GRTH', 'Growth'), ('TRTN', 'Total Return')], db_column='inv_obj_cd', help_text='Objective, e.g. TRTN', max_length=4)),
                ('tm_hzn_cd', models.CharField(choices=[('S', 'Short'), ('M', 'Medium'), ('L', 'Long')], db_column='tm_hzn_cd', help_text='Time horizon, e.g. L', max_length=1)),
                ('liq_need_cd', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIG', 'High')], db_column='liq_need_cd', help_text='Liquidity needs, e.g. MED', max_length=3)),
                ('tgt_ret', models.DecimalField(blank=True, db_column='tgt_ret', decimal_places=4, help_text='Target return, e.g. 0.0800', max_digits=9, null=True)),
                ('vol_cap', models.DecimalField(blank=True, db_column='vol_cap', decimal_places=4, help_text='Volatility cap, e.g. 0.1500', max_digits=7, null=True)),
                ('issuer_max', models.DecimalField(blank=True, db_column='iss_max', decimal_places=4, help_text='Issuer max weight, e.g. 0.0500', max_digits=7, null=True)),
                ('eff_fr_dt', models.DateField(db_column='eff_fr_dt', default=django.utils.timezone.localdate, help_text='Effective from date, e.g. 2026-02-09')),
                ('eff_to_dt', models.DateField(blank=True, db_column='eff_to_dt', help_text='Effective to date, e.g. 2027-02-08', null=True)),
                ('rvw_freq_cd', models.CharField(blank=True, choices=[('MON', 'Monthly'), ('QTR', 'Quarterly'), ('SAA', 'Semi-Annual'), ('ANN', 'Annual'), ('ADH', 'Ad hoc')], db_column='rvw_freq_cd', help_text='Review frequency, e.g. QTR', max_length=3, null=True)),
                ('nxt_rvw_due_dt', models.DateField(blank=True, db_column='nxt_rvw_due_dt', help_text='Next review due date, e.g. 2026-05-31', null=True)),
                ('is_curr', models.BooleanField(db_column='is_curr', default=False, help_text='Current flag, e.g. True')),
                ('chg_rsn', models.CharField(blank=True, db_column='chg_rsn', help_text='Change reason, e.g. Updated risk limits', max_length=240, null=True)),
                ('aprv_by', models.IntegerField(blank=True, db_column='aprv_by', help_text='Approver user id, e.g. 101', null=True)),
                ('aprv_ts', models.DateTimeField(blank=True, db_column='aprv_ts', help_text='Approval timestamp', null=True)),
                ('doc_id', models.BigIntegerField(blank=True, db_column='doc_id', help_text='Signed IPS doc id, e.g. 555101', null=True)),
                ('crt_by', models.IntegerField(db_column='crt_by', default=101, help_text='Created by user id, e.g. 101')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, db_column='crt_ts', help_text='Created timestamp')),
                ('upd_ts', models.DateTimeField(auto_now=True, db_column='upd_ts', help_text='Updated timestamp')),
            ],
            options={
                'db_table': 'px_ips_ver',
            },
        ),
        migrations.RemoveField(
            model_name='ips',
            name='mandate',
        ),
        migrations.RemoveField(
            model_name='ips',
            name='portfolio',
        ),
        migrations.RemoveConstraint(
            model_name='mandate',
            name='ck_mand_dt_range',
        ),
        migrations.RemoveIndex(
            model_name='mandate',
            name='ix_mand_inv_sts',
        ),
        migrations.RemoveIndex(
            model_name='mandate',
            name='ix_mand_auth_sts',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='approval_mode',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='benchmark',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='fee_schedule',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='inception_dt',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='mandate_id',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='mandate_name',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='reporting_delivery',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='reporting_frequency',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='rm',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='termination_dt',
        ),
        migrations.AddField(
            model_name='mandate',
            name='aprv_md_cd',
            field=models.CharField(choices=[('PRE', 'Pre-trade approval'), ('PST', 'Post-trade acknowledgement'), ('NON', 'None')], db_column='aprv_md_cd', default='PRE', help_text='Approval mode, e.g. PRE', max_length=3),
        ),
        migrations.AddField(
            model_name='mandate',
            name='auth_cd',
            field=models.CharField(choices=[('DIS', 'Discretionary'), ('ADV', 'Advisory'), ('MOD', 'Model-only'), ('SIG', 'Signal-only')], db_column='auth_cd', default='SIG', help_text='Authority, e.g. DIS', max_length=3),
        ),
        migrations.AddField(
            model_name='mandate',
            name='bmk',
            field=models.ForeignKey(blank=True, db_column='bmk_id', help_text='Default benchmark, e.g. MSCI World', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='masters.benchmark'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='doc_id',
            field=models.BigIntegerField(blank=True, db_column='doc_id', help_text='Signed mandate doc id, e.g. 555001', null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='fee_sched',
            field=models.ForeignKey(blank=True, db_column='fee_sched_id', help_text='Default fee schedule, e.g. 1% mgmt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='masters.feeschedule'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='incp_dt',
            field=models.DateField(db_column='incp_dt', default=django.utils.timezone.localdate, help_text='Mandate start date, e.g. 2026-02-09'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mand_cd',
            field=models.CharField(db_column='mand_cd', db_index=True, default='MAND__001', help_text='Mandate code, e.g. MAND_BAL_001', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mand_id',
            field=models.BigAutoField(db_column='mand_id', help_text='Mandate key, e.g. 3001', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='mand_nm',
            field=models.CharField(blank=True, db_column='mand_nm', help_text='Mandate name, e.g. Family Balanced', max_length=140),
        ),
        migrations.AddField(
            model_name='mandate',
            name='rpt_dlvr_txt',
            field=models.CharField(blank=True, db_column='rpt_dlvr_txt', help_text='Reporting delivery, e.g. Email PDF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='rpt_freq_txt',
            field=models.CharField(blank=True, db_column='rpt_freq_txt', help_text='Reporting frequency, e.g. Quarterly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='sign_dt',
            field=models.DateField(blank=True, db_column='sign_dt', help_text='Signed date, e.g. 2026-02-10', null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='sts_cd',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], db_column='sts_cd', default='ACT', help_text='Status, e.g. ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='mandate',
            name='term_dt',
            field=models.DateField(blank=True, db_column='term_dt', help_text='Mandate end date, e.g. 2027-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='base_ccy',
            field=models.ForeignKey(db_column='base_ccy_id', help_text='Mandate base currency, e.g. USD', on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=101, help_text='User id, e.g. 101'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='investor',
            field=models.ForeignKey(db_column='inv_id', help_text='Owning investor, e.g. INV_000123', on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='crm.investor'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp'),
        ),
        migrations.AddField(
            model_name='ipsversion',
            name='mandate',
            field=models.ForeignKey(db_column='mand_id', help_text='Parent mandate, e.g. MAND_BAL_001', on_delete=django.db.models.deletion.CASCADE, related_name='ips_versions', to='policies.mandate'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='act_ips_ver',
            field=models.ForeignKey(blank=True, db_column='act_ips_ver_id', help_text='Current IPS version pointer, e.g. ips_ver_id=9001', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='policies.ipsversion'),
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['investor', 'sts_cd'], name='ix_mand_inv_sts'),
        ),
        migrations.AddIndex(
            model_name='mandate',
            index=models.Index(fields=['mand_cd'], name='ix_mand_cd'),
        ),
        migrations.AddConstraint(
            model_name='mandate',
            constraint=models.CheckConstraint(condition=models.Q(('term_dt__isnull', True), ('term_dt__gt', models.F('incp_dt')), _connector='OR'), name='ck_mand_dt_range'),
        ),
    ]
