# Generated by Django 5.2.10 on 2026-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_ipsversion_remove_ips_mandate_remove_ips_portfolio_and_more'),
        ('portfolio', '0004_portfolioaccountmap_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPS',
        ),
        migrations.AddIndex(
            model_name='ipsversion',
            index=models.Index(fields=['mandate', 'is_curr'], name='ix_ips_mand_curr'),
        ),
        migrations.AddIndex(
            model_name='ipsversion',
            index=models.Index(fields=['mandate', 'eff_fr_dt'], name='ix_ips_mand_eff'),
        ),
        migrations.AddIndex(
            model_name='ipsversion',
            index=models.Index(fields=['sts_cd'], name='ix_ips_sts'),
        ),
        migrations.AddConstraint(
            model_name='ipsversion',
            constraint=models.UniqueConstraint(fields=('mandate', 'ver_no'), name='uq_ips_mand_verno'),
        ),
        migrations.AddConstraint(
            model_name='ipsversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_curr', True)), fields=('mandate',), name='uq_ips_one_curr_per_mand'),
        ),
        migrations.AddConstraint(
            model_name='ipsversion',
            constraint=models.CheckConstraint(condition=models.Q(('eff_to_dt__isnull', True), ('eff_to_dt__gt', models.F('eff_fr_dt')), _connector='OR'), name='ck_ips_eff_dt_range'),
        ),
    ]
