# Generated by Django 5.2.10 on 2026-02-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_delete_ips_ipsversion_ix_ips_mand_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='mand_cd',
            field=models.CharField(db_column='mand_cd', db_index=True, help_text='Mandate code, e.g. MAND_BAL_001', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='mand_nm',
            field=models.CharField(db_column='mand_nm', help_text='Mandate name, e.g. Family Balanced', max_length=140),
        ),
    ]
