# Generated by Django 5.2.10 on 2026-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_mandate_mand_cd_alter_mandate_mand_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='rpt_freq_txt',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], default='Q', help_text='ReportingMode, e.g. QUARTERLY', max_length=3),
        ),
    ]
