# Generated by Django 5.2.10 on 2026-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_alter_mandate_rpt_freq_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='rpt_dlvr_txt',
            field=models.CharField(choices=[('E', 'Email'), ('T', 'Text'), ('P', 'PUSH_NOTICE'), ('W', 'Whatsapp'), ('O', 'Other')], db_column='rpt_dlvr_txt', default='E', help_text='Reporting delivery, e.g. Email PDF', max_length=3),
        ),
    ]
