# Generated by Django 5.2.10 on 2026-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_mandate_rpt_dlvr_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='pm_discretion_allowed',
            field=models.BooleanField(default=True, help_text='If False, PM cannot trade on their own discretion; only client-directed trades allowed.'),
        ),
    ]
