from django.db import models
from django.utils import timezone


class CashLedger(models.Model):
    """
    Cash movements generated by trades and corporate actions.
    Supports pending (trade date) vs settled (value date).
    """

    class EntryType(models.TextChoices):
        TRADE = "TRD", "Trade"
        FEE = "FEE", "Fee"
        TAX = "TAX", "Tax"
        DEPOSIT = "DEP", "Deposit"
        WITHDRAWAL = "WDR", "Withdrawal"
        DIVIDEND = "DIV", "Dividend"
        INTEREST = "INT", "Interest"
        FX = "FX", "FX Transfer"
        ADJ = "ADJ", "Adjustment"

    class Status(models.TextChoices):
        PENDING = "PND", "Pending"
        SETTLED = "SET", "Settled"
        CANCELLED = "CXL", "Cancelled"

    cash_id = models.BigAutoField(primary_key=True, db_column="cash_id")

    acct = models.ForeignKey(
        "portfolio.Account",
        on_delete=models.PROTECT,
        related_name="cash_ledger_entries",
        db_column="acct_id",
        db_index=True,
        help_text="Account impacted by this cash entry.",
    )

    ccy = models.ForeignKey(
        "masters.Currency",
        on_delete=models.PROTECT,
        related_name="cash_ledger_entries",
        db_column="ccy_id",
        help_text="Currency of the cash entry.",
    )

    amt = models.DecimalField(
        max_digits=28,
        decimal_places=10,
        db_column="amt",
        help_text="Signed amount. Positive=inflow, Negative=outflow.",
    )

    trd = models.ForeignKey(
        "ibor.IborTrade",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="cash_ledger_entries",
        db_column="trd_id",
        help_text="Optional link to the trade that generated this cash movement.",
    )

    typ_cd = models.CharField(
        max_length=3,
        choices=EntryType.choices,
        default=EntryType.TRADE,
        db_column="typ_cd",
        db_index=True,
        help_text="Cash entry type (trade, fee, dividend, etc.).",
    )

    eff_dt = models.DateField(
        null=True,
        blank=True,
        db_column="eff_dt",
        db_index=True,
        help_text="Value/settlement date when cash becomes effective (settled).",
    )

    book_ts = models.DateTimeField(
        default=timezone.now,
        db_column="book_ts",
        db_index=True,
        help_text="Book timestamp (when entry was recorded).",
    )

    sts_cd = models.CharField(
        max_length=3,
        choices=Status.choices,
        default=Status.PENDING,
        db_column="sts_cd",
        db_index=True,
        help_text="Pending vs settled. A nightly job can flip PND->SET when eff_dt <= today.",
    )

    ref_txt = models.CharField(
        max_length=120,
        blank=True,
        default="",
        db_column="ref_txt",
        help_text="Reference text (bank ref, broker ref, narrative).",
    )

    # audit
    crt_by = models.IntegerField(default=101, db_column="crt_by", help_text="Created by user id.")
    crt_ts = models.DateTimeField(auto_now_add=True, db_column="crt_ts", help_text="Create timestamp.")
    upd_ts = models.DateTimeField(auto_now=True, db_column="upd_ts", help_text="Update timestamp.")

    class Meta:
        db_table = "px_cash_led"
        verbose_name = "Cash Ledger Entry"
        verbose_name_plural = "Cash Ledger"
        ordering = ["-book_ts"]
        indexes = [
            models.Index(fields=["acct", "ccy", "sts_cd"], name="ix_cash_acct_ccy_sts"),
            models.Index(fields=["eff_dt", "sts_cd"], name="ix_cash_eff_sts"),
        ]

    def __str__(self) -> str:
        return f"{self.cash_id} {self.ccy_id} {self.amt} {self.sts_cd}"
