# Generated by Django 5.2.10 on 2026-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='assumed_tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Assumed tax rate of investor 0.0500', max_digits=7),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(blank=True, help_text="Investor's email", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='id_expiry',
            field=models.DateField(blank=True, help_text='ID expiry date', null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='id_number',
            field=models.CharField(blank=True, help_text='ID number in text', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='id_type',
            field=models.CharField(blank=True, choices=[('PASS', 'Passport'), ('EID', 'Emirates ID'), ('NID', 'National ID'), ('OTR', 'Other')], help_text='ID type Passport, License, ID-Card', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_name',
            field=models.CharField(help_text="Investor's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=models.CharField(blank=True, help_text="Investor's phone number in text", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='source_of_funds',
            field=models.CharField(blank=True, help_text='Source of funds e.g. short-term use for transaction', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='source_of_wealth',
            field=models.CharField(blank=True, help_text='Source of wealth e.g. long-term use for client Profile', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch name of the RM e.g. Investment', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the RM', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the RM', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='rm_name',
            field=models.CharField(help_text='Name of the RM', max_length=120),
        ),
        migrations.AlterField(
            model_name='rm',
            name='team',
            field=models.CharField(blank=True, help_text='Team of the RM e.g. Investment', max_length=80, null=True),
        ),
    ]
