# Generated by Django 5.2.10 on 2026-02-09 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_investor_assumed_tax_rate_alter_investor_email_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investor',
            name='investor_investo_86c487_idx',
        ),
        migrations.RemoveIndex(
            model_name='investor',
            name='investor_aml_ris_e7182e_idx',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='aml_risk_rating',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='assumed_tax_rate',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='client_classification',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='id_expiry',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investor_id',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investor_name',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investor_status',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='kyc_review_date',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='next_kyc_review_due',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='pep_flag',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='risk_profile_id',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='sanctions_screened_date',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='source_of_funds',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='source_of_wealth',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='tax_residency_country',
        ),
        migrations.RemoveField(
            model_name='rm',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rm',
            name='rm_name',
        ),
        migrations.RemoveField(
            model_name='rm',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rm',
            name='team',
        ),
        migrations.AddField(
            model_name='investor',
            name='addr_ctry',
            field=models.ForeignKey(blank=True, db_column='addr_ctry_id', help_text='Address country, e.g. UAE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_address', to='masters.country'),
        ),
        migrations.AddField(
            model_name='investor',
            name='aml_risk_cd',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], db_column='aml_risk_cd', default='L', help_text='AML risk, e.g. M', max_length=1),
        ),
        migrations.AddField(
            model_name='investor',
            name='assum_tax_rt',
            field=models.DecimalField(db_column='assum_tax_rt', decimal_places=4, default=0, help_text='Assumed tax rate, e.g. 0.0500', max_digits=7),
        ),
        migrations.AddField(
            model_name='investor',
            name='client_class_cd',
            field=models.CharField(choices=[('RET', 'Retail'), ('PRO', 'Professional'), ('ECP', 'Eligible Counterparty')], db_column='client_class_cd', default='RET', help_text='Client class, e.g. RET', max_length=3),
        ),
        migrations.AddField(
            model_name='investor',
            name='id_exp_dt',
            field=models.DateField(blank=True, db_column='id_exp_dt', help_text='ID expiry date, e.g. 2030-12-31', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='id_no',
            field=models.CharField(blank=True, db_column='id_no', help_text='ID number, e.g. A12345678', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='id_tp_cd',
            field=models.CharField(blank=True, choices=[('PASS', 'Passport'), ('EID', 'Emirates ID'), ('NID', 'National ID'), ('OTR', 'Other')], db_column='id_tp_cd', help_text='ID type, e.g. PASS', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='incp_dt',
            field=models.DateField(blank=True, db_column='incp_dt', help_text='Investor onboarding date, e.g. 2026-02-09', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='inv_cd',
            field=models.CharField(blank=True, db_column='inv_cd', db_index=True, help_text='Investor code, e.g. INV_000123', max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='inv_id',
            field=models.BigAutoField(db_column='inv_id', help_text='Investor key, e.g. 2001', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='investor',
            name='inv_nm',
            field=models.CharField(db_column='inv_nm', default='', help_text='Investor name, e.g. Raza Family Office', max_length=200),
        ),
        migrations.AddField(
            model_name='investor',
            name='inv_sts_cd',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('PRO', 'Prospect'), ('CLS', 'Closed'), ('DOR', 'Dormant')], db_column='inv_sts_cd', default='PRO', help_text='Investor status, e.g. PRO', max_length=3),
        ),
        migrations.AddField(
            model_name='investor',
            name='kyc_nxt_due_dt',
            field=models.DateField(blank=True, db_column='kyc_nxt_due_dt', help_text='Next KYC due date, e.g. 2027-01-15', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='kyc_rvw_dt',
            field=models.DateField(blank=True, db_column='kyc_rvw_dt', help_text='KYC last review date, e.g. 2026-01-15', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='kyc_sts_cd',
            field=models.CharField(choices=[('OPN', 'Opened'), ('IPR', 'In Progress'), ('CMP', 'Completed'), ('EXP', 'Expired'), ('RJD', 'Rejected'), ('WCD', 'Waiting Client Docs')], db_column='kyc_sts_cd', default='OPN', help_text='KYC status, e.g. OPN', max_length=3),
        ),
        migrations.AddField(
            model_name='investor',
            name='pep_flg',
            field=models.BooleanField(db_column='pep_flg', default=False, help_text='PEP flag, e.g. False'),
        ),
        migrations.AddField(
            model_name='investor',
            name='sanc_scrn_dt',
            field=models.DateField(blank=True, db_column='sanc_scrn_dt', help_text='Sanctions screened date, e.g. 2026-02-01', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='sof_txt',
            field=models.CharField(blank=True, db_column='sof_txt', help_text='Source of funds, e.g. Salary / Business', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='sow_txt',
            field=models.CharField(blank=True, db_column='sow_txt', help_text='Source of wealth, e.g. Real estate / Inheritance', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='tax_res_ctry',
            field=models.ForeignKey(blank=True, db_column='tax_res_ctry_id', help_text='Tax residency country, e.g. PAK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_tax_residency', to='masters.country'),
        ),
        migrations.AddField(
            model_name='investor',
            name='tax_sts_cd',
            field=models.CharField(choices=[('FIL', 'Filer'), ('NFI', 'Non-Filer'), ('NA', 'N/A')], db_column='tax_sts_cd', default='NA', help_text='Tax status, e.g. FIL', max_length=3),
        ),
        migrations.AddField(
            model_name='rm',
            name='branch_nm',
            field=models.CharField(blank=True, db_column='branch_nm', help_text='Branch, e.g. Abu Dhabi', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rm',
            name='rm_cd',
            field=models.CharField(db_column='rm_cd', db_index=True, default='RM_UAE_001', help_text='RM code, e.g. RM_UAE_001', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='rm',
            name='rm_id',
            field=models.BigAutoField(db_column='rm_id', help_text='RM key, e.g. 1001', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rm',
            name='rm_nm',
            field=models.CharField(db_column='rm_nm', help_text='RM name, e.g. Ali Khan', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='rm',
            name='sts_cd',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], db_column='sts_cd', default='ACT', help_text='Status, e.g. ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='rm',
            name='team_nm',
            field=models.CharField(blank=True, db_column='team_nm', help_text='Team, e.g. Private Wealth', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=101, help_text='User id, e.g. 101'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(blank=True, db_column='email', help_text='Investor email, e.g. raza@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', help_text='Investor phone, e.g. +971501234567', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='rm',
            field=models.ForeignKey(blank=True, db_column='rm_id', help_text='Coverage RM, e.g. RM_UAE_001', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='crm.rm'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=101, help_text='User id, e.g. 101'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='email',
            field=models.EmailField(blank=True, db_column='email', help_text='RM email, e.g. ali@firm.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', help_text='RM phone, e.g. +971501234567', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['inv_sts_cd', 'kyc_sts_cd'], name='ix_inv_sts_kyc'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['aml_risk_cd', 'pep_flg'], name='ix_inv_aml_pep'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['rm'], name='ix_inv_rm'),
        ),
        migrations.AddIndex(
            model_name='rm',
            index=models.Index(fields=['rm_cd'], name='ix_rm_cd'),
        ),
        migrations.AddIndex(
            model_name='rm',
            index=models.Index(fields=['sts_cd'], name='ix_rm_sts'),
        ),
        migrations.AlterModelTable(
            name='investor',
            table='px_inv_dim',
        ),
        migrations.AlterModelTable(
            name='rm',
            table='px_rm_dim',
        ),
    ]
