# Generated by Django 5.2.10 on 2026-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_investor_investor_investo_86c487_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='inv_nm',
            field=models.CharField(db_column='inv_nm', help_text='Investor name, e.g. Raza Family Office', max_length=200),
        ),
        migrations.AlterField(
            model_name='rm',
            name='rm_cd',
            field=models.CharField(db_column='rm_cd', db_index=True, help_text='RM code, e.g. RM_UAE_001', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='rm',
            name='rm_nm',
            field=models.CharField(db_column='rm_nm', help_text='RM name, e.g. Ali Khan', max_length=120),
        ),
    ]
