# Generated by Django 5.2.10 on 2026-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_rm_rm_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rm',
            name='rm_nm',
            field=models.CharField(db_column='rm_nm', help_text='RM name, e.g. Ali Khan', max_length=120),
        ),
    ]
