# Generated by Django 5.2.10 on 2026-01-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=80, null=True)),
                ('branch', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rm',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('client_classification', models.CharField(choices=[('RET', 'Retail'), ('PRO', 'Professional'), ('ECP', 'Eligible Counterparty')], default='RET', max_length=3)),
                ('id_type', models.CharField(blank=True, choices=[('PASS', 'Passport'), ('EID', 'Emirates ID'), ('NID', 'National ID'), ('OTR', 'Other')], max_length=4, null=True)),
                ('id_number', models.CharField(blank=True, max_length=80, null=True)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('investor_status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('PRO', 'Prospect'), ('CLS', 'Closed'), ('DOR', 'Dormant')], default='PRO', max_length=3)),
                ('kyc_review_date', models.DateField(blank=True, null=True)),
                ('next_kyc_review_due', models.DateField(blank=True, null=True)),
                ('aml_risk_rating', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1)),
                ('pep_flag', models.BooleanField(default=False)),
                ('sanctions_screened_date', models.DateField(blank=True, null=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=120, null=True)),
                ('source_of_wealth', models.CharField(blank=True, max_length=120, null=True)),
                ('tax', models.CharField(choices=[('FIL', 'Filer'), ('NFI', 'Non-Filer'), ('NA', 'N/A')], default='NA', max_length=3)),
                ('assumed_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('risk_profile_id', models.IntegerField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('OPN', 'Opened'), ('IPR', 'In Progress'), ('CMP', 'Completed'), ('EXP', 'Expired'), ('RJD', 'Rejected'), ('WCD', 'Waiting Client Docs')], default='OPN', max_length=3)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_country', models.ForeignKey(blank=True, db_column='address_country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_address', to='masters.country')),
                ('tax_residency_country', models.ForeignKey(blank=True, db_column='tax_residency_country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_tax_residency', to='masters.country')),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='crm.rm')),
            ],
            options={
                'db_table': 'investor',
                'indexes': [models.Index(fields=['investor_status', 'kyc_status'], name='investor_investo_86c487_idx'), models.Index(fields=['aml_risk_rating', 'pep_flag'], name='investor_aml_ris_e7182e_idx')],
            },
        ),
    ]
