# Generated by Django 5.2.10 on 2026-01-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code_at_broker', models.CharField(max_length=60)),
                ('account_type', models.CharField(choices=[('BRK', 'Brokerage'), ('CUS', 'Custody'), ('CSH', 'Cash'), ('MRG', 'Margin'), ('PLT', 'Platform')], default='BRK', max_length=3)),
                ('status', models.CharField(choices=[('OPN', 'Open'), ('CLS', 'Closed'), ('SUS', 'Suspended'), ('RST', 'Restricted')], default='OPN', max_length=3)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=101)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='masters.broker')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='masters.currency')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='crm.investor')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=120)),
                ('mandate_type', models.CharField(choices=[('DIS', 'Discretionary'), ('ADV', 'Advisory'), ('EXO', 'Execution-Only')], default='DIS', max_length=3)),
                ('rebalancing_frequency', models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], default='M', max_length=1)),
                ('reporting_frequency', models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], default='M', max_length=1)),
                ('reporting_delivery', models.CharField(choices=[('PRT', 'Portal'), ('EML', 'Email PDF'), ('WAP', 'WhatsApp'), ('SMS', 'SMS'), ('PST', 'Post')], default='EML', max_length=3)),
                ('trading_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('PND', 'Pending Onboarding'), ('SUS', 'Suspended'), ('CLS', 'Closed')], default='PND', max_length=3)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.currency')),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.benchmark')),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.feeschedule')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='crm.investor')),
                ('primary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_portfolios', to='portfolio.account')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['investor', 'status'], name='account_investo_0589ea_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['broker'], name='account_broker__4df0cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('broker', 'account_code_at_broker'), name='uq_account_broker_code'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['investor_id', 'status'], name='portfolio_investo_b53690_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('investor_id', 'portfolio_name'), name='uq_portfolio_investor_name'),
        ),
    ]
