# Generated by Django 5.2.10 on 2026-02-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_benchmark_benchmark_status_f3041e_idx_and_more'),
        ('policies', '0002_alter_mandate_base_ccy'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='uq_portfolio_investor_name',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='portfolio_investo_b53690_idx',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='investor_id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='mandate_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_by',
            field=models.IntegerField(db_column='crt_by', default=101),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ips_override',
            field=models.ForeignKey(blank=True, db_column='ips_ovr_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_overrides', to='policies.ips'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mandate',
            field=models.ForeignKey(blank=True, db_column='mand_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='policies.mandate'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.BigAutoField(db_column='port_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='base_currency',
            field=models.ForeignKey(blank=True, db_column='base_ccy_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='benchmark',
            field=models.ForeignKey(blank=True, db_column='bmk_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.benchmark'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='crt_ts'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='fee_schedule',
            field=models.ForeignKey(blank=True, db_column='fee_sched_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.feeschedule'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='inception_date',
            field=models.DateField(blank=True, db_column='incp_dt', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='next_review_due',
            field=models.DateField(blank=True, db_column='nxt_rvw_due_dt', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(db_column='port_nm', max_length=120),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='primary_account',
            field=models.ForeignKey(blank=True, db_column='prim_acct_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_portfolios', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rebalancing_frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], db_column='rebal_freq_cd', default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='reporting_delivery',
            field=models.CharField(choices=[('PRT', 'Portal'), ('EML', 'Email PDF'), ('WAP', 'WhatsApp'), ('SMS', 'SMS'), ('PST', 'Post')], db_column='rpt_dlvr_cd', default='EML', max_length=3),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='reporting_frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], db_column='rpt_freq_cd', default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('PND', 'Pending Onboarding'), ('SUS', 'Suspended'), ('CLS', 'Closed')], db_column='sts_cd', default='PND', max_length=3),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='trading_enabled',
            field=models.BooleanField(db_column='trd_enbl_flg', default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='upd_ts'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['mandate', 'status'], name='ix_port_mand_sts'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['status'], name='ix_port_sts'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('mandate', 'portfolio_name'), name='uq_port_mand_nm'),
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='px_port_hdr',
        ),
    ]
