# Generated by Django 5.2.10 on 2026-02-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_mandate_base_ccy'),
        ('portfolio', '0002_remove_portfolio_uq_portfolio_investor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='mandate',
            field=models.ForeignKey(db_column='mand_id', on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='policies.mandate'),
        ),
    ]
