# Generated by Django 5.2.10 on 2026-02-09 19:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_investor_investor_investo_86c487_idx_and_more'),
        ('masters', '0009_rename_currency_benchmark_ccy_code_and_more'),
        ('policies', '0003_ipsversion_remove_ips_mandate_remove_ips_portfolio_and_more'),
        ('portfolio', '0003_alter_portfolio_mandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAccountMap',
            fields=[
                ('port_acct_map_id', models.BigAutoField(db_column='port_acct_map_id', help_text='Mapping key, e.g. 9901', primary_key=True, serialize=False)),
                ('role_cd', models.CharField(choices=[('PRI', 'Primary'), ('TRD', 'Trading'), ('CSH', 'Cash'), ('CUS', 'Custody')], db_column='role_cd', default='TRD', help_text='Role, e.g. PRI', max_length=3)),
                ('eff_fr_dt', models.DateField(db_column='eff_fr_dt', default=django.utils.timezone.localdate, help_text='Effective from, e.g. 2026-02-09')),
                ('eff_to_dt', models.DateField(blank=True, db_column='eff_to_dt', help_text='Effective to, e.g. 2027-01-01', null=True)),
                ('is_primary_flg', models.BooleanField(db_column='is_primary_flg', default=False, help_text='Primary mapping flag, e.g. True')),
                ('crt_by', models.IntegerField(db_column='crt_by', default=101, help_text='Created by user id, e.g. 101')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, db_column='crt_ts', help_text='Created timestamp')),
                ('upd_ts', models.DateTimeField(auto_now=True, db_column='upd_ts', help_text='Updated timestamp')),
            ],
            options={
                'db_table': 'px_port_acct_map',
            },
        ),
        migrations.RemoveConstraint(
            model_name='account',
            name='uq_account_broker_code',
        ),
        migrations.RemoveConstraint(
            model_name='portfolio',
            name='uq_port_mand_nm',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_investo_0589ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='ix_port_mand_sts',
        ),
        migrations.RemoveIndex(
            model_name='portfolio',
            name='ix_port_sts',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='ix_acct_broker',
            old_name='account_broker__4df0cf_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_code_at_broker',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='closed_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opened_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='benchmark',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='fee_schedule',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ips_override',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='next_review_due',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='primary_account',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='rebalancing_frequency',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='reporting_delivery',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='reporting_frequency',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='trading_enabled',
        ),
        migrations.AddField(
            model_name='account',
            name='acct_cd',
            field=models.CharField(blank=True, db_column='acct_cd', db_index=True, help_text='Broker account code, e.g. U1234567', max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='acct_id',
            field=models.BigAutoField(db_column='acct_id', help_text='Account key, e.g. 8001', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='account',
            name='acct_tp_cd',
            field=models.CharField(choices=[('BRK', 'Brokerage'), ('CUS', 'Custody'), ('CSH', 'Cash'), ('MRG', 'Margin'), ('PLT', 'Platform')], db_column='acct_tp_cd', default='BRK', help_text='Account type, e.g. BRK', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='ccy',
            field=models.ForeignKey(blank=True, db_column='ccy_id', help_text='Account currency, e.g. AED', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='masters.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='cls_dt',
            field=models.DateField(blank=True, db_column='cls_dt', help_text='Closed date, e.g. 2027-06-30', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opn_dt',
            field=models.DateField(blank=True, db_column='opn_dt', help_text='Opened date, e.g. 2026-02-01', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sts_cd',
            field=models.CharField(choices=[('OPN', 'Open'), ('CLS', 'Closed'), ('SUS', 'Suspended'), ('RST', 'Restricted')], db_column='sts_cd', default='OPN', help_text='Account status, e.g. OPN', max_length=3),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='base_ccy',
            field=models.ForeignKey(blank=True, db_column='base_ccy_id', help_text='Reporting currency, e.g. USD', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.currency'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bmk',
            field=models.ForeignKey(blank=True, db_column='bmk_id', help_text='Portfolio benchmark, e.g. MSCI World', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.benchmark'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cls_dt',
            field=models.DateField(blank=True, db_column='cls_dt', help_text='Portfolio close date, e.g. 2028-12-31', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fee_sched',
            field=models.ForeignKey(blank=True, db_column='fee_sched_id', help_text='Fee schedule override, e.g. 1% mgmt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.feeschedule'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='incp_dt',
            field=models.DateField(blank=True, db_column='incp_dt', help_text='Portfolio inception, e.g. 2026-02-15', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='nxt_rvw_due_dt',
            field=models.DateField(blank=True, db_column='nxt_rvw_due_dt', help_text='Next review due date, e.g. 2026-05-31', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='perf_mthd_cd',
            field=models.CharField(choices=[('TWRR', 'Time-weighted return'), ('MWRR', 'Money-weighted return')], db_column='perf_mthd_cd', default='TWRR', help_text='Perf method, e.g. TWRR', max_length=4),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_cd',
            field=models.CharField(blank=True, db_column='port_cd', db_index=True, help_text='Portfolio code, e.g. PORT_0001', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_id',
            field=models.BigAutoField(db_column='port_id', help_text='Portfolio key, e.g. 7001', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_nm',
            field=models.CharField(blank=True, db_column='port_nm', help_text='Portfolio name, e.g. Balanced Book - Core', max_length=120),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebal_freq_cd',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], db_column='rebal_freq_cd', default='M', help_text='Rebal freq, e.g. M', max_length=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rpt_dlvr_cd',
            field=models.CharField(choices=[('PRT', 'Portal'), ('EML', 'Email PDF'), ('WAP', 'WhatsApp'), ('SMS', 'SMS'), ('PST', 'Post')], db_column='rpt_dlvr_cd', default='EML', help_text='Delivery, e.g. EML', max_length=3),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rpt_freq_cd',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annual')], db_column='rpt_freq_cd', default='M', help_text='Report freq, e.g. Q', max_length=1),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sts_cd',
            field=models.CharField(choices=[('ACT', 'Active'), ('PND', 'Pending Onboarding'), ('SUS', 'Suspended'), ('CLS', 'Closed')], db_column='sts_cd', default='PND', help_text='Status, e.g. PND', max_length=3),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='trd_enbl_flg',
            field=models.BooleanField(db_column='trd_enbl_flg', default=False, help_text='Trading enabled, e.g. True'),
        ),
        migrations.AlterField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(db_column='broker_id', help_text='Broker ref, e.g. IBKR', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='masters.broker'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=101, help_text='User id, e.g. 101'),
        ),
        migrations.AlterField(
            model_name='account',
            name='investor',
            field=models.ForeignKey(db_column='inv_id', help_text='Account owner investor, e.g. INV_000123', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='crm.investor'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_by',
            field=models.IntegerField(db_column='created_by', default=101, help_text='User id, e.g. 101'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='mandate',
            field=models.ForeignKey(db_column='mand_id', help_text='Parent mandate, e.g. MAND_BAL_001', on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='policies.mandate'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['investor', 'sts_cd'], name='ix_acct_inv_sts'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['mandate', 'sts_cd'], name='ix_port_mand_sts'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['sts_cd'], name='ix_port_sts'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('broker', 'acct_cd'), name='uq_acct_broker_cd'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('mandate', 'port_nm'), name='uq_port_mand_nm'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='px_acct_hdr',
        ),
        migrations.AddField(
            model_name='portfolioaccountmap',
            name='account',
            field=models.ForeignKey(db_column='acct_id', help_text='Account, e.g. U1234567', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_links', to='portfolio.account'),
        ),
        migrations.AddField(
            model_name='portfolioaccountmap',
            name='portfolio',
            field=models.ForeignKey(db_column='port_id', help_text='Portfolio, e.g. PORT_0001', on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccountmap',
            index=models.Index(fields=['portfolio'], name='ix_pam_port'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccountmap',
            index=models.Index(fields=['account'], name='ix_pam_acct'),
        ),
        migrations.AddConstraint(
            model_name='portfolioaccountmap',
            constraint=models.CheckConstraint(condition=models.Q(('eff_to_dt__isnull', True), ('eff_to_dt__gt', models.F('eff_fr_dt')), _connector='OR'), name='ck_pam_eff_dt_range'),
        ),
        migrations.AddConstraint(
            model_name='portfolioaccountmap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_flg', True)), fields=('portfolio',), name='uq_pam_one_primary_per_port'),
        ),
    ]
