# Generated by Django 5.2.10 on 2026-02-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioaccountmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='port_cd',
            field=models.CharField(db_column='port_cd', db_index=True, help_text='Portfolio code, e.g. PORT_0001', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_nm',
            field=models.CharField(db_column='port_nm', help_text='Portfolio name, e.g. Balanced Book - Core', max_length=120),
        ),
    ]
