# Generated by Django 5.2.10 on 2026-06-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_broker_exchange'),
        ('portfolio', '0005_alter_portfolio_port_cd_alter_portfolio_port_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='fee_sched',
            field=models.ForeignKey(blank=True, db_column='fee_sched_id', help_text='PF mgmt Fee schedule override, e.g. 1% mgmt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='masters.feeschedule'),
        ),
    ]
