# Generated by Django 5.2.10 on 2026-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('rpt_req_id', models.BigAutoField(db_column='rpt_req_id', help_text='Report request key, e.g. 1', primary_key=True, serialize=False)),
                ('portfolio_id', models.BigIntegerField(db_column='portfolio_id', db_index=True, help_text='FK to px_port_hdr.port_id, e.g. 1')),
                ('period_end_dt', models.DateField(db_column='period_end_dt', help_text='Month-end date for this report, e.g. 2026-05-31')),
                ('market_commentary', models.TextField(blank=True, db_column='market_commentary', default='', help_text='PM market commentary for the month')),
                ('portfolio_commentary', models.TextField(blank=True, db_column='portfolio_commentary', default='', help_text='PM portfolio-specific commentary')),
                ('outlook', models.TextField(blank=True, db_column='outlook', default='', help_text='PM forward outlook and action plan')),
                ('sts_cd', models.CharField(choices=[('DRF', 'Draft'), ('GEN', 'Generated'), ('SNT', 'Sent'), ('FAL', 'Failed')], db_column='sts_cd', default='DRF', help_text='Report status, e.g. DRF', max_length=3)),
                ('pdf_path', models.CharField(blank=True, db_column='pdf_path', default='', help_text='Relative path to generated PDF, e.g. reports/2026-05/PORT_0001.pdf', max_length=512)),
                ('sent_to_email', models.EmailField(blank=True, db_column='sent_to_email', default='', help_text='Email address the report was delivered to', max_length=254)),
                ('generated_at', models.DateTimeField(blank=True, db_column='generated_at', help_text='Timestamp when PDF was successfully generated', null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_column='sent_at', help_text='Timestamp of successful email delivery', null=True)),
                ('error_txt', models.TextField(blank=True, db_column='error_txt', default='', help_text='Error message if generation or delivery failed')),
                ('created_by', models.IntegerField(db_column='created_by', default=101, help_text='User id who triggered the report, e.g. 101')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated timestamp')),
            ],
            options={
                'db_table': 'reporting_request',
                'ordering': ['-period_end_dt'],
                'indexes': [models.Index(fields=['portfolio_id', 'period_end_dt'], name='ix_rpt_port_dt'), models.Index(fields=['sts_cd'], name='ix_rpt_sts'), models.Index(fields=['period_end_dt'], name='ix_rpt_dt')],
                'unique_together': {('portfolio_id', 'period_end_dt')},
            },
        ),
    ]
